//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiniNetBusiness.SiniNetWSSiniestros {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class ubicacionesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string direccionField;
        
        private double latitudField;
        
        private bool latitudFieldSpecified;
        
        private double longitudField;
        
        private bool longitudFieldSpecified;
        
        private string referenciaField;
        
        private int ubicacionIdField;
        
        private bool ubicacionIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
                this.RaisePropertyChanged("latitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latitudSpecified {
            get {
                return this.latitudFieldSpecified;
            }
            set {
                this.latitudFieldSpecified = value;
                this.RaisePropertyChanged("latitudSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
                this.RaisePropertyChanged("longitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longitudSpecified {
            get {
                return this.longitudFieldSpecified;
            }
            set {
                this.longitudFieldSpecified = value;
                this.RaisePropertyChanged("longitudSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int ubicacionId {
            get {
                return this.ubicacionIdField;
            }
            set {
                this.ubicacionIdField = value;
                this.RaisePropertyChanged("ubicacionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ubicacionIdSpecified {
            get {
                return this.ubicacionIdFieldSpecified;
            }
            set {
                this.ubicacionIdFieldSpecified = value;
                this.RaisePropertyChanged("ubicacionIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuariosDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleadosDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class personasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private string nombresField;
        
        private int personalIdField;
        
        private bool personalIdFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int personalId {
            get {
                return this.personalIdField;
            }
            set {
                this.personalIdField = value;
                this.RaisePropertyChanged("personalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personalIdSpecified {
            get {
                return this.personalIdFieldSpecified;
            }
            set {
                this.personalIdFieldSpecified = value;
                this.RaisePropertyChanged("personalIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleadosDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class usuariosDTO : personasDTO {
        
        private string contraseniaField;
        
        private string correoField;
        
        private estadoUsuario estadoField;
        
        private bool estadoFieldSpecified;
        
        private string nombreUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                this.contraseniaField = value;
                this.RaisePropertyChanged("contrasenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoUsuario estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum estadoUsuario {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        INACTIVO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class empleadosDTO : usuariosDTO {
        
        private desempenhoEmpleado desempenioField;
        
        private bool desempenioFieldSpecified;
        
        private tipoEmpleado tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public desempenhoEmpleado desempenio {
            get {
                return this.desempenioField;
            }
            set {
                this.desempenioField = value;
                this.RaisePropertyChanged("desempenio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool desempenioSpecified {
            get {
                return this.desempenioFieldSpecified;
            }
            set {
                this.desempenioFieldSpecified = value;
                this.RaisePropertyChanged("desempenioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipoEmpleado tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum desempenhoEmpleado {
        
        /// <remarks/>
        INACEPTABLE,
        
        /// <remarks/>
        VALIDO,
        
        /// <remarks/>
        SATISFACTORIO,
        
        /// <remarks/>
        SOBRESALIENTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum tipoEmpleado {
        
        /// <remarks/>
        PROCURADOR,
        
        /// <remarks/>
        OPERADOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class siniestrosDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int calificacionServicioField;
        
        private bool calificacionServicioFieldSpecified;
        
        private string descripcionField;
        
        private estadoSiniestro estadoField;
        
        private bool estadoFieldSpecified;
        
        private string fechaHoraField;
        
        private empleadosDTO procuradorField;
        
        private int siniestroIdField;
        
        private bool siniestroIdFieldSpecified;
        
        private ubicacionesDTO ubicacionField;
        
        private bool validezField;
        
        private bool validezFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int calificacionServicio {
            get {
                return this.calificacionServicioField;
            }
            set {
                this.calificacionServicioField = value;
                this.RaisePropertyChanged("calificacionServicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool calificacionServicioSpecified {
            get {
                return this.calificacionServicioFieldSpecified;
            }
            set {
                this.calificacionServicioFieldSpecified = value;
                this.RaisePropertyChanged("calificacionServicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoSiniestro estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public empleadosDTO procurador {
            get {
                return this.procuradorField;
            }
            set {
                this.procuradorField = value;
                this.RaisePropertyChanged("procurador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int siniestroId {
            get {
                return this.siniestroIdField;
            }
            set {
                this.siniestroIdField = value;
                this.RaisePropertyChanged("siniestroId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool siniestroIdSpecified {
            get {
                return this.siniestroIdFieldSpecified;
            }
            set {
                this.siniestroIdFieldSpecified = value;
                this.RaisePropertyChanged("siniestroIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public ubicacionesDTO ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool validez {
            get {
                return this.validezField;
            }
            set {
                this.validezField = value;
                this.RaisePropertyChanged("validez");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validezSpecified {
            get {
                return this.validezFieldSpecified;
            }
            set {
                this.validezFieldSpecified = value;
                this.RaisePropertyChanged("validezSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum estadoSiniestro {
        
        /// <remarks/>
        EN_PROCESO,
        
        /// <remarks/>
        CANCELADO,
        
        /// <remarks/>
        FINALIZADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", ConfigurationName="SiniNetWSSiniestros.Siniestros")]
    public interface Siniestros {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/listarTodosSiniestrosR" +
            "equest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/listarTodosSiniestrosR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestros.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/listarTodosSiniestros/" +
            "Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestros.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/listarTodosSiniestros/" +
            "Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosResponse listarTodosSiniestros(SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/listarTodosSiniestrosR" +
            "equest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/listarTodosSiniestrosR" +
            "esponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosResponse> listarTodosSiniestrosAsync(SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/listarPorEmpleadoSinie" +
            "strosRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/listarPorEmpleadoSinie" +
            "strosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestros.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/listarPorEmpleadoSinie" +
            "stros/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestros.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/listarPorEmpleadoSinie" +
            "stros/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosResponse listarPorEmpleadoSiniestros(SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/listarPorEmpleadoSinie" +
            "strosRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/listarPorEmpleadoSinie" +
            "strosResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosResponse> listarPorEmpleadoSiniestrosAsync(SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/obtenerPorIdSiniestros" +
            "Request", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/obtenerPorIdSiniestros" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestros.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/obtenerPorIdSiniestros" +
            "/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestros.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/obtenerPorIdSiniestros" +
            "/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosResponse obtenerPorIdSiniestros(SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/obtenerPorIdSiniestros" +
            "Request", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Siniestros/obtenerPorIdSiniestros" +
            "Response")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosResponse> obtenerPorIdSiniestrosAsync(SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosSiniestros", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosSiniestrosRequest {
        
        public listarTodosSiniestrosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosSiniestrosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosSiniestrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestros.siniestrosDTO[] @return;
        
        public listarTodosSiniestrosResponse() {
        }
        
        public listarTodosSiniestrosResponse(SiniNetBusiness.SiniNetWSSiniestros.siniestrosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorEmpleadoSiniestros", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorEmpleadoSiniestrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filtro;
        
        public listarPorEmpleadoSiniestrosRequest() {
        }
        
        public listarPorEmpleadoSiniestrosRequest(string filtro) {
            this.filtro = filtro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorEmpleadoSiniestrosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorEmpleadoSiniestrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestros.siniestrosDTO[] @return;
        
        public listarPorEmpleadoSiniestrosResponse() {
        }
        
        public listarPorEmpleadoSiniestrosResponse(SiniNetBusiness.SiniNetWSSiniestros.siniestrosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdSiniestros", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdSiniestrosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int siniestroId;
        
        public obtenerPorIdSiniestrosRequest() {
        }
        
        public obtenerPorIdSiniestrosRequest(int siniestroId) {
            this.siniestroId = siniestroId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdSiniestrosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdSiniestrosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestros.siniestrosDTO @return;
        
        public obtenerPorIdSiniestrosResponse() {
        }
        
        public obtenerPorIdSiniestrosResponse(SiniNetBusiness.SiniNetWSSiniestros.siniestrosDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SiniestrosChannel : SiniNetBusiness.SiniNetWSSiniestros.Siniestros, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiniestrosClient : System.ServiceModel.ClientBase<SiniNetBusiness.SiniNetWSSiniestros.Siniestros>, SiniNetBusiness.SiniNetWSSiniestros.Siniestros {
        
        public SiniestrosClient() {
        }
        
        public SiniestrosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiniestrosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiniestrosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiniestrosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosResponse SiniNetBusiness.SiniNetWSSiniestros.Siniestros.listarTodosSiniestros(SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosRequest request) {
            return base.Channel.listarTodosSiniestros(request);
        }
        
        public SiniNetBusiness.SiniNetWSSiniestros.siniestrosDTO[] listarTodosSiniestros() {
            SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosRequest inValue = new SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosRequest();
            SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosResponse retVal = ((SiniNetBusiness.SiniNetWSSiniestros.Siniestros)(this)).listarTodosSiniestros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosResponse> SiniNetBusiness.SiniNetWSSiniestros.Siniestros.listarTodosSiniestrosAsync(SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosRequest request) {
            return base.Channel.listarTodosSiniestrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosResponse> listarTodosSiniestrosAsync() {
            SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosRequest inValue = new SiniNetBusiness.SiniNetWSSiniestros.listarTodosSiniestrosRequest();
            return ((SiniNetBusiness.SiniNetWSSiniestros.Siniestros)(this)).listarTodosSiniestrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosResponse SiniNetBusiness.SiniNetWSSiniestros.Siniestros.listarPorEmpleadoSiniestros(SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosRequest request) {
            return base.Channel.listarPorEmpleadoSiniestros(request);
        }
        
        public SiniNetBusiness.SiniNetWSSiniestros.siniestrosDTO[] listarPorEmpleadoSiniestros(string filtro) {
            SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosRequest inValue = new SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosRequest();
            inValue.filtro = filtro;
            SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosResponse retVal = ((SiniNetBusiness.SiniNetWSSiniestros.Siniestros)(this)).listarPorEmpleadoSiniestros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosResponse> SiniNetBusiness.SiniNetWSSiniestros.Siniestros.listarPorEmpleadoSiniestrosAsync(SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosRequest request) {
            return base.Channel.listarPorEmpleadoSiniestrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosResponse> listarPorEmpleadoSiniestrosAsync(string filtro) {
            SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosRequest inValue = new SiniNetBusiness.SiniNetWSSiniestros.listarPorEmpleadoSiniestrosRequest();
            inValue.filtro = filtro;
            return ((SiniNetBusiness.SiniNetWSSiniestros.Siniestros)(this)).listarPorEmpleadoSiniestrosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosResponse SiniNetBusiness.SiniNetWSSiniestros.Siniestros.obtenerPorIdSiniestros(SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosRequest request) {
            return base.Channel.obtenerPorIdSiniestros(request);
        }
        
        public SiniNetBusiness.SiniNetWSSiniestros.siniestrosDTO obtenerPorIdSiniestros(int siniestroId) {
            SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosRequest inValue = new SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosRequest();
            inValue.siniestroId = siniestroId;
            SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosResponse retVal = ((SiniNetBusiness.SiniNetWSSiniestros.Siniestros)(this)).obtenerPorIdSiniestros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosResponse> SiniNetBusiness.SiniNetWSSiniestros.Siniestros.obtenerPorIdSiniestrosAsync(SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosRequest request) {
            return base.Channel.obtenerPorIdSiniestrosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosResponse> obtenerPorIdSiniestrosAsync(int siniestroId) {
            SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosRequest inValue = new SiniNetBusiness.SiniNetWSSiniestros.obtenerPorIdSiniestrosRequest();
            inValue.siniestroId = siniestroId;
            return ((SiniNetBusiness.SiniNetWSSiniestros.Siniestros)(this)).obtenerPorIdSiniestrosAsync(inValue);
        }
    }
}
