//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiniNetBusiness.SiniNetWSInvolucrados {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(involucradosDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class personasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private string nombresField;
        
        private int personalIdField;
        
        private bool personalIdFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int personalId {
            get {
                return this.personalIdField;
            }
            set {
                this.personalIdField = value;
                this.RaisePropertyChanged("personalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personalIdSpecified {
            get {
                return this.personalIdFieldSpecified;
            }
            set {
                this.personalIdFieldSpecified = value;
                this.RaisePropertyChanged("personalIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class involucradosDTO : personasDTO {
        
        private tipoInvolucrado tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public tipoInvolucrado tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum tipoInvolucrado {
        
        /// <remarks/>
        CONDUCTOR,
        
        /// <remarks/>
        ASEGURADO,
        
        /// <remarks/>
        AFECTADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", ConfigurationName="SiniNetWSInvolucrados.Involucrados")]
    public interface Involucrados {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarTodosInvolucra" +
            "dosRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarTodosInvolucra" +
            "dosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSInvolucrados.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarTodosInvolucra" +
            "dos/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSInvolucrados.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarTodosInvolucra" +
            "dos/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosResponse listarTodosInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarTodosInvolucra" +
            "dosRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarTodosInvolucra" +
            "dosResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosResponse> listarTodosInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/obtenerPorIdInvolucr" +
            "adosRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/obtenerPorIdInvolucr" +
            "adosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSInvolucrados.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/obtenerPorIdInvolucr" +
            "ados/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSInvolucrados.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/obtenerPorIdInvolucr" +
            "ados/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosResponse obtenerPorIdInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/obtenerPorIdInvolucr" +
            "adosRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/obtenerPorIdInvolucr" +
            "adosResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosResponse> obtenerPorIdInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/modificarInvolucrado" +
            "sRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/modificarInvolucrado" +
            "sResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosResponse modificarInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/modificarInvolucrado" +
            "sRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/modificarInvolucrado" +
            "sResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosResponse> modificarInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/insertarInvolucrados" +
            "Request", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/insertarInvolucrados" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosResponse insertarInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/insertarInvolucrados" +
            "Request", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/insertarInvolucrados" +
            "Response")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosResponse> insertarInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/eliminarInvolucrados" +
            "Request", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/eliminarInvolucrados" +
            "Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSInvolucrados.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/eliminarInvolucrados" +
            "/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSInvolucrados.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/eliminarInvolucrados" +
            "/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosResponse eliminarInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/eliminarInvolucrados" +
            "Request", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/eliminarInvolucrados" +
            "Response")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosResponse> eliminarInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarTodosAsegurado" +
            "sInvolucradosRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarTodosAsegurado" +
            "sInvolucradosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSInvolucrados.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarTodosAsegurado" +
            "sInvolucrados/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSInvolucrados.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarTodosAsegurado" +
            "sInvolucrados/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosResponse listarTodosAseguradosInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarTodosAsegurado" +
            "sInvolucradosRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarTodosAsegurado" +
            "sInvolucradosResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosResponse> listarTodosAseguradosInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarPorNombreApell" +
            "idoPaternoInvolucradosRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarPorNombreApell" +
            "idoPaternoInvolucradosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSInvolucrados.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarPorNombreApell" +
            "idoPaternoInvolucrados/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSInvolucrados.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarPorNombreApell" +
            "idoPaternoInvolucrados/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosResponse listarPorNombreApellidoPaternoInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarPorNombreApell" +
            "idoPaternoInvolucradosRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Involucrados/listarPorNombreApell" +
            "idoPaternoInvolucradosResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosResponse> listarPorNombreApellidoPaternoInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosInvolucrados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosInvolucradosRequest {
        
        public listarTodosInvolucradosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosInvolucradosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosInvolucradosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSInvolucrados.involucradosDTO[] @return;
        
        public listarTodosInvolucradosResponse() {
        }
        
        public listarTodosInvolucradosResponse(SiniNetBusiness.SiniNetWSInvolucrados.involucradosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdInvolucrados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdInvolucradosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int empleadoId;
        
        public obtenerPorIdInvolucradosRequest() {
        }
        
        public obtenerPorIdInvolucradosRequest(int empleadoId) {
            this.empleadoId = empleadoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdInvolucradosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdInvolucradosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSInvolucrados.involucradosDTO @return;
        
        public obtenerPorIdInvolucradosResponse() {
        }
        
        public obtenerPorIdInvolucradosResponse(SiniNetBusiness.SiniNetWSInvolucrados.involucradosDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarInvolucrados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarInvolucradosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSInvolucrados.tipoInvolucrado tipo;
        
        public modificarInvolucradosRequest() {
        }
        
        public modificarInvolucradosRequest(int personalId, string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono, SiniNetBusiness.SiniNetWSInvolucrados.tipoInvolucrado tipo) {
            this.personalId = personalId;
            this.dni = dni;
            this.nombres = nombres;
            this.apellidoPaterno = apellidoPaterno;
            this.apellidoMaterno = apellidoMaterno;
            this.telefono = telefono;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarInvolucradosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarInvolucradosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarInvolucradosResponse() {
        }
        
        public modificarInvolucradosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarInvolucrados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarInvolucradosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSInvolucrados.tipoInvolucrado tipo;
        
        public insertarInvolucradosRequest() {
        }
        
        public insertarInvolucradosRequest(string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono, SiniNetBusiness.SiniNetWSInvolucrados.tipoInvolucrado tipo) {
            this.dni = dni;
            this.nombres = nombres;
            this.apellidoPaterno = apellidoPaterno;
            this.apellidoMaterno = apellidoMaterno;
            this.telefono = telefono;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarInvolucradosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarInvolucradosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarInvolucradosResponse() {
        }
        
        public insertarInvolucradosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarInvolucrados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarInvolucradosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int involucradoId;
        
        public eliminarInvolucradosRequest() {
        }
        
        public eliminarInvolucradosRequest(int involucradoId) {
            this.involucradoId = involucradoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarInvolucradosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarInvolucradosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarInvolucradosResponse() {
        }
        
        public eliminarInvolucradosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosAseguradosInvolucrados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosAseguradosInvolucradosRequest {
        
        public listarTodosAseguradosInvolucradosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosAseguradosInvolucradosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosAseguradosInvolucradosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSInvolucrados.involucradosDTO[] @return;
        
        public listarTodosAseguradosInvolucradosResponse() {
        }
        
        public listarTodosAseguradosInvolucradosResponse(SiniNetBusiness.SiniNetWSInvolucrados.involucradosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorNombreApellidoPaternoInvolucrados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorNombreApellidoPaternoInvolucradosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filtro;
        
        public listarPorNombreApellidoPaternoInvolucradosRequest() {
        }
        
        public listarPorNombreApellidoPaternoInvolucradosRequest(string filtro) {
            this.filtro = filtro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorNombreApellidoPaternoInvolucradosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorNombreApellidoPaternoInvolucradosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSInvolucrados.involucradosDTO[] @return;
        
        public listarPorNombreApellidoPaternoInvolucradosResponse() {
        }
        
        public listarPorNombreApellidoPaternoInvolucradosResponse(SiniNetBusiness.SiniNetWSInvolucrados.involucradosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InvolucradosChannel : SiniNetBusiness.SiniNetWSInvolucrados.Involucrados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InvolucradosClient : System.ServiceModel.ClientBase<SiniNetBusiness.SiniNetWSInvolucrados.Involucrados>, SiniNetBusiness.SiniNetWSInvolucrados.Involucrados {
        
        public InvolucradosClient() {
        }
        
        public InvolucradosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InvolucradosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvolucradosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InvolucradosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosResponse SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.listarTodosInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosRequest request) {
            return base.Channel.listarTodosInvolucrados(request);
        }
        
        public SiniNetBusiness.SiniNetWSInvolucrados.involucradosDTO[] listarTodosInvolucrados() {
            SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosRequest();
            SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosResponse retVal = ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).listarTodosInvolucrados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosResponse> SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.listarTodosInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosRequest request) {
            return base.Channel.listarTodosInvolucradosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosResponse> listarTodosInvolucradosAsync() {
            SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.listarTodosInvolucradosRequest();
            return ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).listarTodosInvolucradosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosResponse SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.obtenerPorIdInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosRequest request) {
            return base.Channel.obtenerPorIdInvolucrados(request);
        }
        
        public SiniNetBusiness.SiniNetWSInvolucrados.involucradosDTO obtenerPorIdInvolucrados(int empleadoId) {
            SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosRequest();
            inValue.empleadoId = empleadoId;
            SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosResponse retVal = ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).obtenerPorIdInvolucrados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosResponse> SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.obtenerPorIdInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosRequest request) {
            return base.Channel.obtenerPorIdInvolucradosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosResponse> obtenerPorIdInvolucradosAsync(int empleadoId) {
            SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.obtenerPorIdInvolucradosRequest();
            inValue.empleadoId = empleadoId;
            return ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).obtenerPorIdInvolucradosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosResponse SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.modificarInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosRequest request) {
            return base.Channel.modificarInvolucrados(request);
        }
        
        public int modificarInvolucrados(int personalId, string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono, SiniNetBusiness.SiniNetWSInvolucrados.tipoInvolucrado tipo) {
            SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosRequest();
            inValue.personalId = personalId;
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            inValue.tipo = tipo;
            SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosResponse retVal = ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).modificarInvolucrados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosResponse> SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.modificarInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosRequest request) {
            return base.Channel.modificarInvolucradosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosResponse> modificarInvolucradosAsync(int personalId, string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono, SiniNetBusiness.SiniNetWSInvolucrados.tipoInvolucrado tipo) {
            SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.modificarInvolucradosRequest();
            inValue.personalId = personalId;
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            inValue.tipo = tipo;
            return ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).modificarInvolucradosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosResponse SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.insertarInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosRequest request) {
            return base.Channel.insertarInvolucrados(request);
        }
        
        public int insertarInvolucrados(string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono, SiniNetBusiness.SiniNetWSInvolucrados.tipoInvolucrado tipo) {
            SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosRequest();
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            inValue.tipo = tipo;
            SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosResponse retVal = ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).insertarInvolucrados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosResponse> SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.insertarInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosRequest request) {
            return base.Channel.insertarInvolucradosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosResponse> insertarInvolucradosAsync(string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono, SiniNetBusiness.SiniNetWSInvolucrados.tipoInvolucrado tipo) {
            SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.insertarInvolucradosRequest();
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            inValue.tipo = tipo;
            return ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).insertarInvolucradosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosResponse SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.eliminarInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosRequest request) {
            return base.Channel.eliminarInvolucrados(request);
        }
        
        public int eliminarInvolucrados(int involucradoId) {
            SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosRequest();
            inValue.involucradoId = involucradoId;
            SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosResponse retVal = ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).eliminarInvolucrados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosResponse> SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.eliminarInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosRequest request) {
            return base.Channel.eliminarInvolucradosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosResponse> eliminarInvolucradosAsync(int involucradoId) {
            SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.eliminarInvolucradosRequest();
            inValue.involucradoId = involucradoId;
            return ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).eliminarInvolucradosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosResponse SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.listarTodosAseguradosInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosRequest request) {
            return base.Channel.listarTodosAseguradosInvolucrados(request);
        }
        
        public SiniNetBusiness.SiniNetWSInvolucrados.involucradosDTO[] listarTodosAseguradosInvolucrados() {
            SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosRequest();
            SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosResponse retVal = ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).listarTodosAseguradosInvolucrados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosResponse> SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.listarTodosAseguradosInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosRequest request) {
            return base.Channel.listarTodosAseguradosInvolucradosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosResponse> listarTodosAseguradosInvolucradosAsync() {
            SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.listarTodosAseguradosInvolucradosRequest();
            return ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).listarTodosAseguradosInvolucradosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosResponse SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.listarPorNombreApellidoPaternoInvolucrados(SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosRequest request) {
            return base.Channel.listarPorNombreApellidoPaternoInvolucrados(request);
        }
        
        public SiniNetBusiness.SiniNetWSInvolucrados.involucradosDTO[] listarPorNombreApellidoPaternoInvolucrados(string filtro) {
            SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosRequest();
            inValue.filtro = filtro;
            SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosResponse retVal = ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).listarPorNombreApellidoPaternoInvolucrados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosResponse> SiniNetBusiness.SiniNetWSInvolucrados.Involucrados.listarPorNombreApellidoPaternoInvolucradosAsync(SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosRequest request) {
            return base.Channel.listarPorNombreApellidoPaternoInvolucradosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosResponse> listarPorNombreApellidoPaternoInvolucradosAsync(string filtro) {
            SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosRequest inValue = new SiniNetBusiness.SiniNetWSInvolucrados.listarPorNombreApellidoPaternoInvolucradosRequest();
            inValue.filtro = filtro;
            return ((SiniNetBusiness.SiniNetWSInvolucrados.Involucrados)(this)).listarPorNombreApellidoPaternoInvolucradosAsync(inValue);
        }
    }
}
