//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiniNetBusiness.SiniNetWSSiniestrosSOAT {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(polizasSOATDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class polizasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private personasDTO aseguradoField;
        
        private estadoPoliza estadoField;
        
        private bool estadoFieldSpecified;
        
        private int polizaIdField;
        
        private bool polizaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public personasDTO asegurado {
            get {
                return this.aseguradoField;
            }
            set {
                this.aseguradoField = value;
                this.RaisePropertyChanged("asegurado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoPoliza estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int polizaId {
            get {
                return this.polizaIdField;
            }
            set {
                this.polizaIdField = value;
                this.RaisePropertyChanged("polizaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool polizaIdSpecified {
            get {
                return this.polizaIdFieldSpecified;
            }
            set {
                this.polizaIdFieldSpecified = value;
                this.RaisePropertyChanged("polizaIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuariosDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleadosDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class personasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private string nombresField;
        
        private int personalIdField;
        
        private bool personalIdFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int personalId {
            get {
                return this.personalIdField;
            }
            set {
                this.personalIdField = value;
                this.RaisePropertyChanged("personalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personalIdSpecified {
            get {
                return this.personalIdFieldSpecified;
            }
            set {
                this.personalIdFieldSpecified = value;
                this.RaisePropertyChanged("personalIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleadosDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class usuariosDTO : personasDTO {
        
        private string contraseniaField;
        
        private string correoField;
        
        private estadoUsuario estadoField;
        
        private bool estadoFieldSpecified;
        
        private string nombreUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                this.contraseniaField = value;
                this.RaisePropertyChanged("contrasenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoUsuario estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum estadoUsuario {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        INACTIVO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class empleadosDTO : usuariosDTO {
        
        private desempenhoEmpleado desempenioField;
        
        private bool desempenioFieldSpecified;
        
        private tipoEmpleado tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public desempenhoEmpleado desempenio {
            get {
                return this.desempenioField;
            }
            set {
                this.desempenioField = value;
                this.RaisePropertyChanged("desempenio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool desempenioSpecified {
            get {
                return this.desempenioFieldSpecified;
            }
            set {
                this.desempenioFieldSpecified = value;
                this.RaisePropertyChanged("desempenioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipoEmpleado tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum desempenhoEmpleado {
        
        /// <remarks/>
        INACEPTABLE,
        
        /// <remarks/>
        VALIDO,
        
        /// <remarks/>
        SATISFACTORIO,
        
        /// <remarks/>
        SOBRESALIENTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum tipoEmpleado {
        
        /// <remarks/>
        PROCURADOR,
        
        /// <remarks/>
        OPERADOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum estadoPoliza {
        
        /// <remarks/>
        VIGENTE,
        
        /// <remarks/>
        VENCIDO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class polizasSOATDTO : polizasDTO {
        
        private int montoACoberturaField;
        
        private bool montoACoberturaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int montoACobertura {
            get {
                return this.montoACoberturaField;
            }
            set {
                this.montoACoberturaField = value;
                this.RaisePropertyChanged("montoACobertura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoACoberturaSpecified {
            get {
                return this.montoACoberturaFieldSpecified;
            }
            set {
                this.montoACoberturaFieldSpecified = value;
                this.RaisePropertyChanged("montoACoberturaSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class centrosDeSaludDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int centroDeSaludIdField;
        
        private bool centroDeSaludIdFieldSpecified;
        
        private string codigoRenipressField;
        
        private string nombreField;
        
        private string telefonoField;
        
        private ubicacionesDTO ubicacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int centroDeSaludId {
            get {
                return this.centroDeSaludIdField;
            }
            set {
                this.centroDeSaludIdField = value;
                this.RaisePropertyChanged("centroDeSaludId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool centroDeSaludIdSpecified {
            get {
                return this.centroDeSaludIdFieldSpecified;
            }
            set {
                this.centroDeSaludIdFieldSpecified = value;
                this.RaisePropertyChanged("centroDeSaludIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string codigoRenipress {
            get {
                return this.codigoRenipressField;
            }
            set {
                this.codigoRenipressField = value;
                this.RaisePropertyChanged("codigoRenipress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public ubicacionesDTO ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class ubicacionesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string direccionField;
        
        private double latitudField;
        
        private bool latitudFieldSpecified;
        
        private double longitudField;
        
        private bool longitudFieldSpecified;
        
        private string referenciaField;
        
        private int ubicacionIdField;
        
        private bool ubicacionIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double latitud {
            get {
                return this.latitudField;
            }
            set {
                this.latitudField = value;
                this.RaisePropertyChanged("latitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool latitudSpecified {
            get {
                return this.latitudFieldSpecified;
            }
            set {
                this.latitudFieldSpecified = value;
                this.RaisePropertyChanged("latitudSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double longitud {
            get {
                return this.longitudField;
            }
            set {
                this.longitudField = value;
                this.RaisePropertyChanged("longitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool longitudSpecified {
            get {
                return this.longitudFieldSpecified;
            }
            set {
                this.longitudFieldSpecified = value;
                this.RaisePropertyChanged("longitudSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
                this.RaisePropertyChanged("referencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int ubicacionId {
            get {
                return this.ubicacionIdField;
            }
            set {
                this.ubicacionIdField = value;
                this.RaisePropertyChanged("ubicacionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ubicacionIdSpecified {
            get {
                return this.ubicacionIdFieldSpecified;
            }
            set {
                this.ubicacionIdFieldSpecified = value;
                this.RaisePropertyChanged("ubicacionIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(siniestrosSOATDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class siniestrosDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int calificacionServicioField;
        
        private bool calificacionServicioFieldSpecified;
        
        private string descripcionField;
        
        private estadoSiniestro estadoField;
        
        private bool estadoFieldSpecified;
        
        private string fechaHoraField;
        
        private empleadosDTO procuradorField;
        
        private int siniestroIdField;
        
        private bool siniestroIdFieldSpecified;
        
        private ubicacionesDTO ubicacionField;
        
        private bool validezField;
        
        private bool validezFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int calificacionServicio {
            get {
                return this.calificacionServicioField;
            }
            set {
                this.calificacionServicioField = value;
                this.RaisePropertyChanged("calificacionServicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool calificacionServicioSpecified {
            get {
                return this.calificacionServicioFieldSpecified;
            }
            set {
                this.calificacionServicioFieldSpecified = value;
                this.RaisePropertyChanged("calificacionServicioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoSiniestro estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
                this.RaisePropertyChanged("fechaHora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public empleadosDTO procurador {
            get {
                return this.procuradorField;
            }
            set {
                this.procuradorField = value;
                this.RaisePropertyChanged("procurador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int siniestroId {
            get {
                return this.siniestroIdField;
            }
            set {
                this.siniestroIdField = value;
                this.RaisePropertyChanged("siniestroId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool siniestroIdSpecified {
            get {
                return this.siniestroIdFieldSpecified;
            }
            set {
                this.siniestroIdFieldSpecified = value;
                this.RaisePropertyChanged("siniestroIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public ubicacionesDTO ubicacion {
            get {
                return this.ubicacionField;
            }
            set {
                this.ubicacionField = value;
                this.RaisePropertyChanged("ubicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public bool validez {
            get {
                return this.validezField;
            }
            set {
                this.validezField = value;
                this.RaisePropertyChanged("validez");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool validezSpecified {
            get {
                return this.validezFieldSpecified;
            }
            set {
                this.validezFieldSpecified = value;
                this.RaisePropertyChanged("validezSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum estadoSiniestro {
        
        /// <remarks/>
        EN_PROCESO,
        
        /// <remarks/>
        CANCELADO,
        
        /// <remarks/>
        FINALIZADO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class siniestrosSOATDTO : siniestrosDTO {
        
        private personasDTO[] afectadosField;
        
        private centrosDeSaludDTO centroDeSaludField;
        
        private string diagnosticoField;
        
        private double gastosMedicosField;
        
        private bool gastosMedicosFieldSpecified;
        
        private polizasSOATDTO polizaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("afectados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public personasDTO[] afectados {
            get {
                return this.afectadosField;
            }
            set {
                this.afectadosField = value;
                this.RaisePropertyChanged("afectados");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public centrosDeSaludDTO centroDeSalud {
            get {
                return this.centroDeSaludField;
            }
            set {
                this.centroDeSaludField = value;
                this.RaisePropertyChanged("centroDeSalud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string diagnostico {
            get {
                return this.diagnosticoField;
            }
            set {
                this.diagnosticoField = value;
                this.RaisePropertyChanged("diagnostico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double gastosMedicos {
            get {
                return this.gastosMedicosField;
            }
            set {
                this.gastosMedicosField = value;
                this.RaisePropertyChanged("gastosMedicos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool gastosMedicosSpecified {
            get {
                return this.gastosMedicosFieldSpecified;
            }
            set {
                this.gastosMedicosFieldSpecified = value;
                this.RaisePropertyChanged("gastosMedicosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public polizasSOATDTO poliza {
            get {
                return this.polizaField;
            }
            set {
                this.polizaField = value;
                this.RaisePropertyChanged("poliza");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", ConfigurationName="SiniNetWSSiniestrosSOAT.SiniestrosSOAT")]
    public interface SiniestrosSOAT {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/obtenerPorIdSinies" +
            "trosSOATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/obtenerPorIdSinies" +
            "trosSOATResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestrosSOAT.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/obtenerPorIdSinies" +
            "trosSOAT/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestrosSOAT.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/obtenerPorIdSinies" +
            "trosSOAT/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(polizasDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(siniestrosDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATResponse obtenerPorIdSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/obtenerPorIdSinies" +
            "trosSOATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/obtenerPorIdSinies" +
            "trosSOATResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATResponse> obtenerPorIdSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/insertarSiniestros" +
            "SOATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/insertarSiniestros" +
            "SOATResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(polizasDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(siniestrosDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATResponse insertarSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/insertarSiniestros" +
            "SOATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/insertarSiniestros" +
            "SOATResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATResponse> insertarSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/modificarSiniestro" +
            "sSOATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/modificarSiniestro" +
            "sSOATResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(polizasDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(siniestrosDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATResponse modificarSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/modificarSiniestro" +
            "sSOATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/modificarSiniestro" +
            "sSOATResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATResponse> modificarSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/reporteSiniestrosS" +
            "OATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/reporteSiniestrosS" +
            "OATResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(polizasDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(siniestrosDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATResponse reporteSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/reporteSiniestrosS" +
            "OATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/reporteSiniestrosS" +
            "OATResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATResponse> reporteSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/eliminarSiniestros" +
            "SOATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/eliminarSiniestros" +
            "SOATResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestrosSOAT.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/eliminarSiniestros" +
            "SOAT/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestrosSOAT.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/eliminarSiniestros" +
            "SOAT/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(polizasDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(siniestrosDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATResponse eliminarSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/eliminarSiniestros" +
            "SOATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/eliminarSiniestros" +
            "SOATResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATResponse> eliminarSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/listarTodosSiniest" +
            "rosSOATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/listarTodosSiniest" +
            "rosSOATResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestrosSOAT.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/listarTodosSiniest" +
            "rosSOAT/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestrosSOAT.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/listarTodosSiniest" +
            "rosSOAT/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(polizasDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(siniestrosDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATResponse listarTodosSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/listarTodosSiniest" +
            "rosSOATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/listarTodosSiniest" +
            "rosSOATResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATResponse> listarTodosSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/listarPorProcurado" +
            "rSiniestrosSOATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/listarPorProcurado" +
            "rSiniestrosSOATResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestrosSOAT.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/listarPorProcurado" +
            "rSiniestrosSOAT/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSSiniestrosSOAT.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/listarPorProcurado" +
            "rSiniestrosSOAT/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(polizasDTO))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(siniestrosDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATResponse listarPorProcuradorSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/listarPorProcurado" +
            "rSiniestrosSOATRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/SiniestrosSOAT/listarPorProcurado" +
            "rSiniestrosSOATResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATResponse> listarPorProcuradorSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdSiniestrosSOAT", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdSiniestrosSOATRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int siniestroId;
        
        public obtenerPorIdSiniestrosSOATRequest() {
        }
        
        public obtenerPorIdSiniestrosSOATRequest(int siniestroId) {
            this.siniestroId = siniestroId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdSiniestrosSOATResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdSiniestrosSOATResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.siniestrosSOATDTO @return;
        
        public obtenerPorIdSiniestrosSOATResponse() {
        }
        
        public obtenerPorIdSiniestrosSOATResponse(SiniNetBusiness.SiniNetWSSiniestrosSOAT.siniestrosSOATDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSiniestrosSOAT", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSiniestrosSOATRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaHora;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.estadoSiniestro estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int calificacionReporte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.ubicacionesDTO ubicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.empleadosDTO procurador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool validez;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.centrosDeSaludDTO centroDeSalud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double gastosMedicos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string diagnostico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute("afectados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.personasDTO[] afectados;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.polizasSOATDTO poliza;
        
        public insertarSiniestrosSOATRequest() {
        }
        
        public insertarSiniestrosSOATRequest(string descripcion, string fechaHora, SiniNetBusiness.SiniNetWSSiniestrosSOAT.estadoSiniestro estado, int calificacionReporte, SiniNetBusiness.SiniNetWSSiniestrosSOAT.ubicacionesDTO ubicacion, SiniNetBusiness.SiniNetWSSiniestrosSOAT.empleadosDTO procurador, bool validez, SiniNetBusiness.SiniNetWSSiniestrosSOAT.centrosDeSaludDTO centroDeSalud, double gastosMedicos, string diagnostico, SiniNetBusiness.SiniNetWSSiniestrosSOAT.personasDTO[] afectados, SiniNetBusiness.SiniNetWSSiniestrosSOAT.polizasSOATDTO poliza) {
            this.descripcion = descripcion;
            this.fechaHora = fechaHora;
            this.estado = estado;
            this.calificacionReporte = calificacionReporte;
            this.ubicacion = ubicacion;
            this.procurador = procurador;
            this.validez = validez;
            this.centroDeSalud = centroDeSalud;
            this.gastosMedicos = gastosMedicos;
            this.diagnostico = diagnostico;
            this.afectados = afectados;
            this.poliza = poliza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSiniestrosSOATResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSiniestrosSOATResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarSiniestrosSOATResponse() {
        }
        
        public insertarSiniestrosSOATResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarSiniestrosSOAT", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarSiniestrosSOATRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int siniestroId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaHora;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.estadoSiniestro estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int calificacionReporte;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.ubicacionesDTO ubicacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.empleadosDTO procurador;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool validez;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.centrosDeSaludDTO centroDeSalud;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double gastosMedicos;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string diagnostico;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute("afectados", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.personasDTO[] afectados;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=12)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.polizasSOATDTO poliza;
        
        public modificarSiniestrosSOATRequest() {
        }
        
        public modificarSiniestrosSOATRequest(int siniestroId, string descripcion, string fechaHora, SiniNetBusiness.SiniNetWSSiniestrosSOAT.estadoSiniestro estado, int calificacionReporte, SiniNetBusiness.SiniNetWSSiniestrosSOAT.ubicacionesDTO ubicacion, SiniNetBusiness.SiniNetWSSiniestrosSOAT.empleadosDTO procurador, bool validez, SiniNetBusiness.SiniNetWSSiniestrosSOAT.centrosDeSaludDTO centroDeSalud, double gastosMedicos, string diagnostico, SiniNetBusiness.SiniNetWSSiniestrosSOAT.personasDTO[] afectados, SiniNetBusiness.SiniNetWSSiniestrosSOAT.polizasSOATDTO poliza) {
            this.siniestroId = siniestroId;
            this.descripcion = descripcion;
            this.fechaHora = fechaHora;
            this.estado = estado;
            this.calificacionReporte = calificacionReporte;
            this.ubicacion = ubicacion;
            this.procurador = procurador;
            this.validez = validez;
            this.centroDeSalud = centroDeSalud;
            this.gastosMedicos = gastosMedicos;
            this.diagnostico = diagnostico;
            this.afectados = afectados;
            this.poliza = poliza;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarSiniestrosSOATResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarSiniestrosSOATResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarSiniestrosSOATResponse() {
        }
        
        public modificarSiniestrosSOATResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteSiniestrosSOAT", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class reporteSiniestrosSOATRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int siniestroId;
        
        public reporteSiniestrosSOATRequest() {
        }
        
        public reporteSiniestrosSOATRequest(int siniestroId) {
            this.siniestroId = siniestroId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteSiniestrosSOATResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class reporteSiniestrosSOATResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public reporteSiniestrosSOATResponse() {
        }
        
        public reporteSiniestrosSOATResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarSiniestrosSOAT", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarSiniestrosSOATRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int siniestroId;
        
        public eliminarSiniestrosSOATRequest() {
        }
        
        public eliminarSiniestrosSOATRequest(int siniestroId) {
            this.siniestroId = siniestroId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarSiniestrosSOATResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarSiniestrosSOATResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarSiniestrosSOATResponse() {
        }
        
        public eliminarSiniestrosSOATResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosSiniestrosSOAT", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosSiniestrosSOATRequest {
        
        public listarTodosSiniestrosSOATRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosSiniestrosSOATResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosSiniestrosSOATResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.siniestrosSOATDTO[] @return;
        
        public listarTodosSiniestrosSOATResponse() {
        }
        
        public listarTodosSiniestrosSOATResponse(SiniNetBusiness.SiniNetWSSiniestrosSOAT.siniestrosSOATDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorProcuradorSiniestrosSOAT", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorProcuradorSiniestrosSOATRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idProcurador;
        
        public listarPorProcuradorSiniestrosSOATRequest() {
        }
        
        public listarPorProcuradorSiniestrosSOATRequest(int idProcurador) {
            this.idProcurador = idProcurador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorProcuradorSiniestrosSOATResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorProcuradorSiniestrosSOATResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.siniestrosSOATDTO[] @return;
        
        public listarPorProcuradorSiniestrosSOATResponse() {
        }
        
        public listarPorProcuradorSiniestrosSOATResponse(SiniNetBusiness.SiniNetWSSiniestrosSOAT.siniestrosSOATDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SiniestrosSOATChannel : SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiniestrosSOATClient : System.ServiceModel.ClientBase<SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT>, SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT {
        
        public SiniestrosSOATClient() {
        }
        
        public SiniestrosSOATClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiniestrosSOATClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiniestrosSOATClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiniestrosSOATClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATResponse SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.obtenerPorIdSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATRequest request) {
            return base.Channel.obtenerPorIdSiniestrosSOAT(request);
        }
        
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.siniestrosSOATDTO obtenerPorIdSiniestrosSOAT(int siniestroId) {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATRequest();
            inValue.siniestroId = siniestroId;
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATResponse retVal = ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).obtenerPorIdSiniestrosSOAT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATResponse> SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.obtenerPorIdSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATRequest request) {
            return base.Channel.obtenerPorIdSiniestrosSOATAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATResponse> obtenerPorIdSiniestrosSOATAsync(int siniestroId) {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.obtenerPorIdSiniestrosSOATRequest();
            inValue.siniestroId = siniestroId;
            return ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).obtenerPorIdSiniestrosSOATAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATResponse SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.insertarSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATRequest request) {
            return base.Channel.insertarSiniestrosSOAT(request);
        }
        
        public int insertarSiniestrosSOAT(string descripcion, string fechaHora, SiniNetBusiness.SiniNetWSSiniestrosSOAT.estadoSiniestro estado, int calificacionReporte, SiniNetBusiness.SiniNetWSSiniestrosSOAT.ubicacionesDTO ubicacion, SiniNetBusiness.SiniNetWSSiniestrosSOAT.empleadosDTO procurador, bool validez, SiniNetBusiness.SiniNetWSSiniestrosSOAT.centrosDeSaludDTO centroDeSalud, double gastosMedicos, string diagnostico, SiniNetBusiness.SiniNetWSSiniestrosSOAT.personasDTO[] afectados, SiniNetBusiness.SiniNetWSSiniestrosSOAT.polizasSOATDTO poliza) {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATRequest();
            inValue.descripcion = descripcion;
            inValue.fechaHora = fechaHora;
            inValue.estado = estado;
            inValue.calificacionReporte = calificacionReporte;
            inValue.ubicacion = ubicacion;
            inValue.procurador = procurador;
            inValue.validez = validez;
            inValue.centroDeSalud = centroDeSalud;
            inValue.gastosMedicos = gastosMedicos;
            inValue.diagnostico = diagnostico;
            inValue.afectados = afectados;
            inValue.poliza = poliza;
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATResponse retVal = ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).insertarSiniestrosSOAT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATResponse> SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.insertarSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATRequest request) {
            return base.Channel.insertarSiniestrosSOATAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATResponse> insertarSiniestrosSOATAsync(string descripcion, string fechaHora, SiniNetBusiness.SiniNetWSSiniestrosSOAT.estadoSiniestro estado, int calificacionReporte, SiniNetBusiness.SiniNetWSSiniestrosSOAT.ubicacionesDTO ubicacion, SiniNetBusiness.SiniNetWSSiniestrosSOAT.empleadosDTO procurador, bool validez, SiniNetBusiness.SiniNetWSSiniestrosSOAT.centrosDeSaludDTO centroDeSalud, double gastosMedicos, string diagnostico, SiniNetBusiness.SiniNetWSSiniestrosSOAT.personasDTO[] afectados, SiniNetBusiness.SiniNetWSSiniestrosSOAT.polizasSOATDTO poliza) {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.insertarSiniestrosSOATRequest();
            inValue.descripcion = descripcion;
            inValue.fechaHora = fechaHora;
            inValue.estado = estado;
            inValue.calificacionReporte = calificacionReporte;
            inValue.ubicacion = ubicacion;
            inValue.procurador = procurador;
            inValue.validez = validez;
            inValue.centroDeSalud = centroDeSalud;
            inValue.gastosMedicos = gastosMedicos;
            inValue.diagnostico = diagnostico;
            inValue.afectados = afectados;
            inValue.poliza = poliza;
            return ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).insertarSiniestrosSOATAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATResponse SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.modificarSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATRequest request) {
            return base.Channel.modificarSiniestrosSOAT(request);
        }
        
        public int modificarSiniestrosSOAT(int siniestroId, string descripcion, string fechaHora, SiniNetBusiness.SiniNetWSSiniestrosSOAT.estadoSiniestro estado, int calificacionReporte, SiniNetBusiness.SiniNetWSSiniestrosSOAT.ubicacionesDTO ubicacion, SiniNetBusiness.SiniNetWSSiniestrosSOAT.empleadosDTO procurador, bool validez, SiniNetBusiness.SiniNetWSSiniestrosSOAT.centrosDeSaludDTO centroDeSalud, double gastosMedicos, string diagnostico, SiniNetBusiness.SiniNetWSSiniestrosSOAT.personasDTO[] afectados, SiniNetBusiness.SiniNetWSSiniestrosSOAT.polizasSOATDTO poliza) {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATRequest();
            inValue.siniestroId = siniestroId;
            inValue.descripcion = descripcion;
            inValue.fechaHora = fechaHora;
            inValue.estado = estado;
            inValue.calificacionReporte = calificacionReporte;
            inValue.ubicacion = ubicacion;
            inValue.procurador = procurador;
            inValue.validez = validez;
            inValue.centroDeSalud = centroDeSalud;
            inValue.gastosMedicos = gastosMedicos;
            inValue.diagnostico = diagnostico;
            inValue.afectados = afectados;
            inValue.poliza = poliza;
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATResponse retVal = ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).modificarSiniestrosSOAT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATResponse> SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.modificarSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATRequest request) {
            return base.Channel.modificarSiniestrosSOATAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATResponse> modificarSiniestrosSOATAsync(int siniestroId, string descripcion, string fechaHora, SiniNetBusiness.SiniNetWSSiniestrosSOAT.estadoSiniestro estado, int calificacionReporte, SiniNetBusiness.SiniNetWSSiniestrosSOAT.ubicacionesDTO ubicacion, SiniNetBusiness.SiniNetWSSiniestrosSOAT.empleadosDTO procurador, bool validez, SiniNetBusiness.SiniNetWSSiniestrosSOAT.centrosDeSaludDTO centroDeSalud, double gastosMedicos, string diagnostico, SiniNetBusiness.SiniNetWSSiniestrosSOAT.personasDTO[] afectados, SiniNetBusiness.SiniNetWSSiniestrosSOAT.polizasSOATDTO poliza) {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.modificarSiniestrosSOATRequest();
            inValue.siniestroId = siniestroId;
            inValue.descripcion = descripcion;
            inValue.fechaHora = fechaHora;
            inValue.estado = estado;
            inValue.calificacionReporte = calificacionReporte;
            inValue.ubicacion = ubicacion;
            inValue.procurador = procurador;
            inValue.validez = validez;
            inValue.centroDeSalud = centroDeSalud;
            inValue.gastosMedicos = gastosMedicos;
            inValue.diagnostico = diagnostico;
            inValue.afectados = afectados;
            inValue.poliza = poliza;
            return ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).modificarSiniestrosSOATAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATResponse SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.reporteSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATRequest request) {
            return base.Channel.reporteSiniestrosSOAT(request);
        }
        
        public byte[] reporteSiniestrosSOAT(int siniestroId) {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATRequest();
            inValue.siniestroId = siniestroId;
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATResponse retVal = ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).reporteSiniestrosSOAT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATResponse> SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.reporteSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATRequest request) {
            return base.Channel.reporteSiniestrosSOATAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATResponse> reporteSiniestrosSOATAsync(int siniestroId) {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.reporteSiniestrosSOATRequest();
            inValue.siniestroId = siniestroId;
            return ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).reporteSiniestrosSOATAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATResponse SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.eliminarSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATRequest request) {
            return base.Channel.eliminarSiniestrosSOAT(request);
        }
        
        public int eliminarSiniestrosSOAT(int siniestroId) {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATRequest();
            inValue.siniestroId = siniestroId;
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATResponse retVal = ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).eliminarSiniestrosSOAT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATResponse> SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.eliminarSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATRequest request) {
            return base.Channel.eliminarSiniestrosSOATAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATResponse> eliminarSiniestrosSOATAsync(int siniestroId) {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.eliminarSiniestrosSOATRequest();
            inValue.siniestroId = siniestroId;
            return ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).eliminarSiniestrosSOATAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATResponse SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.listarTodosSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATRequest request) {
            return base.Channel.listarTodosSiniestrosSOAT(request);
        }
        
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.siniestrosSOATDTO[] listarTodosSiniestrosSOAT() {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATRequest();
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATResponse retVal = ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).listarTodosSiniestrosSOAT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATResponse> SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.listarTodosSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATRequest request) {
            return base.Channel.listarTodosSiniestrosSOATAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATResponse> listarTodosSiniestrosSOATAsync() {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarTodosSiniestrosSOATRequest();
            return ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).listarTodosSiniestrosSOATAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATResponse SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.listarPorProcuradorSiniestrosSOAT(SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATRequest request) {
            return base.Channel.listarPorProcuradorSiniestrosSOAT(request);
        }
        
        public SiniNetBusiness.SiniNetWSSiniestrosSOAT.siniestrosSOATDTO[] listarPorProcuradorSiniestrosSOAT(int idProcurador) {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATRequest();
            inValue.idProcurador = idProcurador;
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATResponse retVal = ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).listarPorProcuradorSiniestrosSOAT(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATResponse> SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT.listarPorProcuradorSiniestrosSOATAsync(SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATRequest request) {
            return base.Channel.listarPorProcuradorSiniestrosSOATAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATResponse> listarPorProcuradorSiniestrosSOATAsync(int idProcurador) {
            SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATRequest inValue = new SiniNetBusiness.SiniNetWSSiniestrosSOAT.listarPorProcuradorSiniestrosSOATRequest();
            inValue.idProcurador = idProcurador;
            return ((SiniNetBusiness.SiniNetWSSiniestrosSOAT.SiniestrosSOAT)(this)).listarPorProcuradorSiniestrosSOATAsync(inValue);
        }
    }
}
