//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiniNetBusiness.SiniNetWSEmpleados {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(usuariosDTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleadosDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class personasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private string nombresField;
        
        private int personalIdField;
        
        private bool personalIdFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int personalId {
            get {
                return this.personalIdField;
            }
            set {
                this.personalIdField = value;
                this.RaisePropertyChanged("personalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personalIdSpecified {
            get {
                return this.personalIdFieldSpecified;
            }
            set {
                this.personalIdFieldSpecified = value;
                this.RaisePropertyChanged("personalIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(empleadosDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class usuariosDTO : personasDTO {
        
        private string contraseniaField;
        
        private string correoField;
        
        private estadoUsuario estadoField;
        
        private bool estadoFieldSpecified;
        
        private string nombreUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string contrasenia {
            get {
                return this.contraseniaField;
            }
            set {
                this.contraseniaField = value;
                this.RaisePropertyChanged("contrasenia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string correo {
            get {
                return this.correoField;
            }
            set {
                this.correoField = value;
                this.RaisePropertyChanged("correo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public estadoUsuario estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombreUsuario {
            get {
                return this.nombreUsuarioField;
            }
            set {
                this.nombreUsuarioField = value;
                this.RaisePropertyChanged("nombreUsuario");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum estadoUsuario {
        
        /// <remarks/>
        ACTIVO,
        
        /// <remarks/>
        INACTIVO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class empleadosDTO : usuariosDTO {
        
        private desempenhoEmpleado desempenioField;
        
        private bool desempenioFieldSpecified;
        
        private tipoEmpleado tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public desempenhoEmpleado desempenio {
            get {
                return this.desempenioField;
            }
            set {
                this.desempenioField = value;
                this.RaisePropertyChanged("desempenio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool desempenioSpecified {
            get {
                return this.desempenioFieldSpecified;
            }
            set {
                this.desempenioFieldSpecified = value;
                this.RaisePropertyChanged("desempenioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipoEmpleado tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum desempenhoEmpleado {
        
        /// <remarks/>
        INACEPTABLE,
        
        /// <remarks/>
        VALIDO,
        
        /// <remarks/>
        SATISFACTORIO,
        
        /// <remarks/>
        SOBRESALIENTE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum tipoEmpleado {
        
        /// <remarks/>
        PROCURADOR,
        
        /// <remarks/>
        OPERADOR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", ConfigurationName="SiniNetWSEmpleados.Empleados")]
    public interface Empleados {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarTodosEmpleadosReq" +
            "uest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarTodosEmpleadosRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSEmpleados.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarTodosEmpleados/Fa" +
            "ult/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSEmpleados.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarTodosEmpleados/Fa" +
            "ult/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosResponse listarTodosEmpleados(SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarTodosEmpleadosReq" +
            "uest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarTodosEmpleadosRes" +
            "ponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosResponse> listarTodosEmpleadosAsync(SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/eliminarEmpleadosReques" +
            "t", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/eliminarEmpleadosRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSEmpleados.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/eliminarEmpleados/Fault" +
            "/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSEmpleados.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/eliminarEmpleados/Fault" +
            "/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosResponse eliminarEmpleados(SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/eliminarEmpleadosReques" +
            "t", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/eliminarEmpleadosRespon" +
            "se")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosResponse> eliminarEmpleadosAsync(SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/modificarEmpleadosReque" +
            "st", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/modificarEmpleadosRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosResponse modificarEmpleados(SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/modificarEmpleadosReque" +
            "st", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/modificarEmpleadosRespo" +
            "nse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosResponse> modificarEmpleadosAsync(SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarProcuradoresReque" +
            "st", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarProcuradoresRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSEmpleados.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarProcuradores/Faul" +
            "t/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSEmpleados.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarProcuradores/Faul" +
            "t/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresResponse listarProcuradores(SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarProcuradoresReque" +
            "st", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarProcuradoresRespo" +
            "nse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresResponse> listarProcuradoresAsync(SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/insertarEmpleadosReques" +
            "t", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/insertarEmpleadosRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosResponse insertarEmpleados(SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/insertarEmpleadosReques" +
            "t", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/insertarEmpleadosRespon" +
            "se")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosResponse> insertarEmpleadosAsync(SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/obtenerPorIdEmpleadosRe" +
            "quest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/obtenerPorIdEmpleadosRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSEmpleados.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/obtenerPorIdEmpleados/F" +
            "ault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSEmpleados.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/obtenerPorIdEmpleados/F" +
            "ault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosResponse obtenerPorIdEmpleados(SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/obtenerPorIdEmpleadosRe" +
            "quest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/obtenerPorIdEmpleadosRe" +
            "sponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosResponse> obtenerPorIdEmpleadosAsync(SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/reporteCalificacionProc" +
            "uradorRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/reporteCalificacionProc" +
            "uradorResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorResponse reporteCalificacionProcurador(SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/reporteCalificacionProc" +
            "uradorRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/reporteCalificacionProc" +
            "uradorResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorResponse> reporteCalificacionProcuradorAsync(SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarPorNombreApellido" +
            "PaternoTipoEmpleadosRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarPorNombreApellido" +
            "PaternoTipoEmpleadosResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSEmpleados.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarPorNombreApellido" +
            "PaternoTipoEmpleados/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSEmpleados.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarPorNombreApellido" +
            "PaternoTipoEmpleados/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(personasDTO))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosResponse listarPorNombreApellidoPaternoTipoEmpleados(SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarPorNombreApellido" +
            "PaternoTipoEmpleadosRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Empleados/listarPorNombreApellido" +
            "PaternoTipoEmpleadosResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosResponse> listarPorNombreApellidoPaternoTipoEmpleadosAsync(SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosEmpleados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosEmpleadosRequest {
        
        public listarTodosEmpleadosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosEmpleadosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosEmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSEmpleados.empleadosDTO[] @return;
        
        public listarTodosEmpleadosResponse() {
        }
        
        public listarTodosEmpleadosResponse(SiniNetBusiness.SiniNetWSEmpleados.empleadosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpleados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEmpleadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int empleadoId;
        
        public eliminarEmpleadosRequest() {
        }
        
        public eliminarEmpleadosRequest(int empleadoId) {
            this.empleadoId = empleadoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarEmpleadosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarEmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarEmpleadosResponse() {
        }
        
        public eliminarEmpleadosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEmpleados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarEmpleadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSEmpleados.estadoUsuario estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSEmpleados.desempenhoEmpleado desempenio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=11)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSEmpleados.tipoEmpleado tipo;
        
        public modificarEmpleadosRequest() {
        }
        
        public modificarEmpleadosRequest(int personalId, string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono, string nombreUsuario, string contrasenia, string correo, SiniNetBusiness.SiniNetWSEmpleados.estadoUsuario estado, SiniNetBusiness.SiniNetWSEmpleados.desempenhoEmpleado desempenio, SiniNetBusiness.SiniNetWSEmpleados.tipoEmpleado tipo) {
            this.personalId = personalId;
            this.dni = dni;
            this.nombres = nombres;
            this.apellidoPaterno = apellidoPaterno;
            this.apellidoMaterno = apellidoMaterno;
            this.telefono = telefono;
            this.nombreUsuario = nombreUsuario;
            this.contrasenia = contrasenia;
            this.correo = correo;
            this.estado = estado;
            this.desempenio = desempenio;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarEmpleadosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarEmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarEmpleadosResponse() {
        }
        
        public modificarEmpleadosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProcuradores", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProcuradoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filtroProcurador;
        
        public listarProcuradoresRequest() {
        }
        
        public listarProcuradoresRequest(string filtroProcurador) {
            this.filtroProcurador = filtroProcurador;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProcuradoresResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProcuradoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSEmpleados.empleadosDTO[] @return;
        
        public listarProcuradoresResponse() {
        }
        
        public listarProcuradoresResponse(SiniNetBusiness.SiniNetWSEmpleados.empleadosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEmpleados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEmpleadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombreUsuario;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string contrasenia;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string correo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSEmpleados.estadoUsuario estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=9)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSEmpleados.desempenhoEmpleado desempenio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=10)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSEmpleados.tipoEmpleado tipo;
        
        public insertarEmpleadosRequest() {
        }
        
        public insertarEmpleadosRequest(string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono, string nombreUsuario, string contrasenia, string correo, SiniNetBusiness.SiniNetWSEmpleados.estadoUsuario estado, SiniNetBusiness.SiniNetWSEmpleados.desempenhoEmpleado desempenio, SiniNetBusiness.SiniNetWSEmpleados.tipoEmpleado tipo) {
            this.dni = dni;
            this.nombres = nombres;
            this.apellidoPaterno = apellidoPaterno;
            this.apellidoMaterno = apellidoMaterno;
            this.telefono = telefono;
            this.nombreUsuario = nombreUsuario;
            this.contrasenia = contrasenia;
            this.correo = correo;
            this.estado = estado;
            this.desempenio = desempenio;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEmpleadosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEmpleadosResponse() {
        }
        
        public insertarEmpleadosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdEmpleados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdEmpleadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int empleadoId;
        
        public obtenerPorIdEmpleadosRequest() {
        }
        
        public obtenerPorIdEmpleadosRequest(int empleadoId) {
            this.empleadoId = empleadoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdEmpleadosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdEmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSEmpleados.empleadosDTO @return;
        
        public obtenerPorIdEmpleadosResponse() {
        }
        
        public obtenerPorIdEmpleadosResponse(SiniNetBusiness.SiniNetWSEmpleados.empleadosDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteCalificacionProcurador", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class reporteCalificacionProcuradorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int procuradorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaFin;
        
        public reporteCalificacionProcuradorRequest() {
        }
        
        public reporteCalificacionProcuradorRequest(int procuradorId, string fechaInicio, string fechaFin) {
            this.procuradorId = procuradorId;
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteCalificacionProcuradorResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class reporteCalificacionProcuradorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] @return;
        
        public reporteCalificacionProcuradorResponse() {
        }
        
        public reporteCalificacionProcuradorResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorNombreApellidoPaternoTipoEmpleados", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorNombreApellidoPaternoTipoEmpleadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filtro;
        
        public listarPorNombreApellidoPaternoTipoEmpleadosRequest() {
        }
        
        public listarPorNombreApellidoPaternoTipoEmpleadosRequest(string filtro) {
            this.filtro = filtro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorNombreApellidoPaternoTipoEmpleadosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorNombreApellidoPaternoTipoEmpleadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSEmpleados.empleadosDTO[] @return;
        
        public listarPorNombreApellidoPaternoTipoEmpleadosResponse() {
        }
        
        public listarPorNombreApellidoPaternoTipoEmpleadosResponse(SiniNetBusiness.SiniNetWSEmpleados.empleadosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpleadosChannel : SiniNetBusiness.SiniNetWSEmpleados.Empleados, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadosClient : System.ServiceModel.ClientBase<SiniNetBusiness.SiniNetWSEmpleados.Empleados>, SiniNetBusiness.SiniNetWSEmpleados.Empleados {
        
        public EmpleadosClient() {
        }
        
        public EmpleadosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpleadosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpleadosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosResponse SiniNetBusiness.SiniNetWSEmpleados.Empleados.listarTodosEmpleados(SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosRequest request) {
            return base.Channel.listarTodosEmpleados(request);
        }
        
        public SiniNetBusiness.SiniNetWSEmpleados.empleadosDTO[] listarTodosEmpleados() {
            SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosRequest();
            SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosResponse retVal = ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).listarTodosEmpleados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosResponse> SiniNetBusiness.SiniNetWSEmpleados.Empleados.listarTodosEmpleadosAsync(SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosRequest request) {
            return base.Channel.listarTodosEmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosResponse> listarTodosEmpleadosAsync() {
            SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.listarTodosEmpleadosRequest();
            return ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).listarTodosEmpleadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosResponse SiniNetBusiness.SiniNetWSEmpleados.Empleados.eliminarEmpleados(SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosRequest request) {
            return base.Channel.eliminarEmpleados(request);
        }
        
        public int eliminarEmpleados(int empleadoId) {
            SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosRequest();
            inValue.empleadoId = empleadoId;
            SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosResponse retVal = ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).eliminarEmpleados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosResponse> SiniNetBusiness.SiniNetWSEmpleados.Empleados.eliminarEmpleadosAsync(SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosRequest request) {
            return base.Channel.eliminarEmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosResponse> eliminarEmpleadosAsync(int empleadoId) {
            SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.eliminarEmpleadosRequest();
            inValue.empleadoId = empleadoId;
            return ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).eliminarEmpleadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosResponse SiniNetBusiness.SiniNetWSEmpleados.Empleados.modificarEmpleados(SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosRequest request) {
            return base.Channel.modificarEmpleados(request);
        }
        
        public int modificarEmpleados(int personalId, string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono, string nombreUsuario, string contrasenia, string correo, SiniNetBusiness.SiniNetWSEmpleados.estadoUsuario estado, SiniNetBusiness.SiniNetWSEmpleados.desempenhoEmpleado desempenio, SiniNetBusiness.SiniNetWSEmpleados.tipoEmpleado tipo) {
            SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosRequest();
            inValue.personalId = personalId;
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            inValue.nombreUsuario = nombreUsuario;
            inValue.contrasenia = contrasenia;
            inValue.correo = correo;
            inValue.estado = estado;
            inValue.desempenio = desempenio;
            inValue.tipo = tipo;
            SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosResponse retVal = ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).modificarEmpleados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosResponse> SiniNetBusiness.SiniNetWSEmpleados.Empleados.modificarEmpleadosAsync(SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosRequest request) {
            return base.Channel.modificarEmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosResponse> modificarEmpleadosAsync(int personalId, string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono, string nombreUsuario, string contrasenia, string correo, SiniNetBusiness.SiniNetWSEmpleados.estadoUsuario estado, SiniNetBusiness.SiniNetWSEmpleados.desempenhoEmpleado desempenio, SiniNetBusiness.SiniNetWSEmpleados.tipoEmpleado tipo) {
            SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.modificarEmpleadosRequest();
            inValue.personalId = personalId;
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            inValue.nombreUsuario = nombreUsuario;
            inValue.contrasenia = contrasenia;
            inValue.correo = correo;
            inValue.estado = estado;
            inValue.desempenio = desempenio;
            inValue.tipo = tipo;
            return ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).modificarEmpleadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresResponse SiniNetBusiness.SiniNetWSEmpleados.Empleados.listarProcuradores(SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresRequest request) {
            return base.Channel.listarProcuradores(request);
        }
        
        public SiniNetBusiness.SiniNetWSEmpleados.empleadosDTO[] listarProcuradores(string filtroProcurador) {
            SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresRequest();
            inValue.filtroProcurador = filtroProcurador;
            SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresResponse retVal = ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).listarProcuradores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresResponse> SiniNetBusiness.SiniNetWSEmpleados.Empleados.listarProcuradoresAsync(SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresRequest request) {
            return base.Channel.listarProcuradoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresResponse> listarProcuradoresAsync(string filtroProcurador) {
            SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.listarProcuradoresRequest();
            inValue.filtroProcurador = filtroProcurador;
            return ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).listarProcuradoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosResponse SiniNetBusiness.SiniNetWSEmpleados.Empleados.insertarEmpleados(SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosRequest request) {
            return base.Channel.insertarEmpleados(request);
        }
        
        public int insertarEmpleados(string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono, string nombreUsuario, string contrasenia, string correo, SiniNetBusiness.SiniNetWSEmpleados.estadoUsuario estado, SiniNetBusiness.SiniNetWSEmpleados.desempenhoEmpleado desempenio, SiniNetBusiness.SiniNetWSEmpleados.tipoEmpleado tipo) {
            SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosRequest();
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            inValue.nombreUsuario = nombreUsuario;
            inValue.contrasenia = contrasenia;
            inValue.correo = correo;
            inValue.estado = estado;
            inValue.desempenio = desempenio;
            inValue.tipo = tipo;
            SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosResponse retVal = ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).insertarEmpleados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosResponse> SiniNetBusiness.SiniNetWSEmpleados.Empleados.insertarEmpleadosAsync(SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosRequest request) {
            return base.Channel.insertarEmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosResponse> insertarEmpleadosAsync(string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono, string nombreUsuario, string contrasenia, string correo, SiniNetBusiness.SiniNetWSEmpleados.estadoUsuario estado, SiniNetBusiness.SiniNetWSEmpleados.desempenhoEmpleado desempenio, SiniNetBusiness.SiniNetWSEmpleados.tipoEmpleado tipo) {
            SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.insertarEmpleadosRequest();
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            inValue.nombreUsuario = nombreUsuario;
            inValue.contrasenia = contrasenia;
            inValue.correo = correo;
            inValue.estado = estado;
            inValue.desempenio = desempenio;
            inValue.tipo = tipo;
            return ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).insertarEmpleadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosResponse SiniNetBusiness.SiniNetWSEmpleados.Empleados.obtenerPorIdEmpleados(SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosRequest request) {
            return base.Channel.obtenerPorIdEmpleados(request);
        }
        
        public SiniNetBusiness.SiniNetWSEmpleados.empleadosDTO obtenerPorIdEmpleados(int empleadoId) {
            SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosRequest();
            inValue.empleadoId = empleadoId;
            SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosResponse retVal = ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).obtenerPorIdEmpleados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosResponse> SiniNetBusiness.SiniNetWSEmpleados.Empleados.obtenerPorIdEmpleadosAsync(SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosRequest request) {
            return base.Channel.obtenerPorIdEmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosResponse> obtenerPorIdEmpleadosAsync(int empleadoId) {
            SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.obtenerPorIdEmpleadosRequest();
            inValue.empleadoId = empleadoId;
            return ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).obtenerPorIdEmpleadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorResponse SiniNetBusiness.SiniNetWSEmpleados.Empleados.reporteCalificacionProcurador(SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorRequest request) {
            return base.Channel.reporteCalificacionProcurador(request);
        }
        
        public byte[] reporteCalificacionProcurador(int procuradorId, string fechaInicio, string fechaFin) {
            SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorRequest();
            inValue.procuradorId = procuradorId;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorResponse retVal = ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).reporteCalificacionProcurador(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorResponse> SiniNetBusiness.SiniNetWSEmpleados.Empleados.reporteCalificacionProcuradorAsync(SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorRequest request) {
            return base.Channel.reporteCalificacionProcuradorAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorResponse> reporteCalificacionProcuradorAsync(int procuradorId, string fechaInicio, string fechaFin) {
            SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.reporteCalificacionProcuradorRequest();
            inValue.procuradorId = procuradorId;
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            return ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).reporteCalificacionProcuradorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosResponse SiniNetBusiness.SiniNetWSEmpleados.Empleados.listarPorNombreApellidoPaternoTipoEmpleados(SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosRequest request) {
            return base.Channel.listarPorNombreApellidoPaternoTipoEmpleados(request);
        }
        
        public SiniNetBusiness.SiniNetWSEmpleados.empleadosDTO[] listarPorNombreApellidoPaternoTipoEmpleados(string filtro) {
            SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosRequest();
            inValue.filtro = filtro;
            SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosResponse retVal = ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).listarPorNombreApellidoPaternoTipoEmpleados(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosResponse> SiniNetBusiness.SiniNetWSEmpleados.Empleados.listarPorNombreApellidoPaternoTipoEmpleadosAsync(SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosRequest request) {
            return base.Channel.listarPorNombreApellidoPaternoTipoEmpleadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosResponse> listarPorNombreApellidoPaternoTipoEmpleadosAsync(string filtro) {
            SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosRequest inValue = new SiniNetBusiness.SiniNetWSEmpleados.listarPorNombreApellidoPaternoTipoEmpleadosRequest();
            inValue.filtro = filtro;
            return ((SiniNetBusiness.SiniNetWSEmpleados.Empleados)(this)).listarPorNombreApellidoPaternoTipoEmpleadosAsync(inValue);
        }
    }
}
