//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiniNetBusiness.SiniNetWSPolizasVehiculares {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class personasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private string nombresField;
        
        private int personalIdField;
        
        private bool personalIdFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int personalId {
            get {
                return this.personalIdField;
            }
            set {
                this.personalIdField = value;
                this.RaisePropertyChanged("personalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personalIdSpecified {
            get {
                return this.personalIdFieldSpecified;
            }
            set {
                this.personalIdFieldSpecified = value;
                this.RaisePropertyChanged("personalIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", ConfigurationName="SiniNetWSPolizasVehiculares.PolizasVehiculares")]
    public interface PolizasVehiculares {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/insertarPoliza" +
            "sVehicularesRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/insertarPoliza" +
            "sVehicularesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesResponse insertarPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/insertarPoliza" +
            "sVehicularesRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/insertarPoliza" +
            "sVehicularesResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesResponse> insertarPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/eliminarPoliza" +
            "sVehicularesRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/eliminarPoliza" +
            "sVehicularesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPolizasVehiculares.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/eliminarPoliza" +
            "sVehiculares/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPolizasVehiculares.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/eliminarPoliza" +
            "sVehiculares/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesResponse eliminarPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/eliminarPoliza" +
            "sVehicularesRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/eliminarPoliza" +
            "sVehicularesResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesResponse> eliminarPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/obtenerPorIdPo" +
            "lizasVehicularesRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/obtenerPorIdPo" +
            "lizasVehicularesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPolizasVehiculares.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/obtenerPorIdPo" +
            "lizasVehiculares/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPolizasVehiculares.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/obtenerPorIdPo" +
            "lizasVehiculares/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesResponse obtenerPorIdPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/obtenerPorIdPo" +
            "lizasVehicularesRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/obtenerPorIdPo" +
            "lizasVehicularesResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesResponse> obtenerPorIdPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/listarTodosPol" +
            "izasVehicularesRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/listarTodosPol" +
            "izasVehicularesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPolizasVehiculares.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/listarTodosPol" +
            "izasVehiculares/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPolizasVehiculares.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/listarTodosPol" +
            "izasVehiculares/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesResponse listarTodosPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/listarTodosPol" +
            "izasVehicularesRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/listarTodosPol" +
            "izasVehicularesResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesResponse> listarTodosPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/modificarPoliz" +
            "asVehicularesRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/modificarPoliz" +
            "asVehicularesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesResponse modificarPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/modificarPoliz" +
            "asVehicularesRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/modificarPoliz" +
            "asVehicularesResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesResponse> modificarPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/listarPorNombr" +
            "eApellidoAseguradoPolizasVehicularesRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/listarPorNombr" +
            "eApellidoAseguradoPolizasVehicularesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPolizasVehiculares.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/listarPorNombr" +
            "eApellidoAseguradoPolizasVehiculares/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPolizasVehiculares.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/listarPorNombr" +
            "eApellidoAseguradoPolizasVehiculares/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesResponse listarPorNombreApellidoAseguradoPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/listarPorNombr" +
            "eApellidoAseguradoPolizasVehicularesRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/PolizasVehiculares/listarPorNombr" +
            "eApellidoAseguradoPolizasVehicularesResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesResponse> listarPorNombreApellidoAseguradoPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum estadoPoliza {
        
        /// <remarks/>
        VIGENTE,
        
        /// <remarks/>
        VENCIDO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum tipoPolizaVehicular {
        
        /// <remarks/>
        TODORIESGO,
        
        /// <remarks/>
        PERDIDATOTAL,
        
        /// <remarks/>
        RESPONSABILIDADCIVIL,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPolizasVehiculares", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPolizasVehicularesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPolizasVehiculares.personasDTO asegurado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPolizasVehiculares.estadoPoliza estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPolizasVehiculares.tipoPolizaVehicular tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int porcentajeCobertura;
        
        public insertarPolizasVehicularesRequest() {
        }
        
        public insertarPolizasVehicularesRequest(SiniNetBusiness.SiniNetWSPolizasVehiculares.personasDTO asegurado, SiniNetBusiness.SiniNetWSPolizasVehiculares.estadoPoliza estado, SiniNetBusiness.SiniNetWSPolizasVehiculares.tipoPolizaVehicular tipo, int porcentajeCobertura) {
            this.asegurado = asegurado;
            this.estado = estado;
            this.tipo = tipo;
            this.porcentajeCobertura = porcentajeCobertura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPolizasVehicularesResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPolizasVehicularesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPolizasVehicularesResponse() {
        }
        
        public insertarPolizasVehicularesResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPolizasVehiculares", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPolizasVehicularesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int polizaId;
        
        public eliminarPolizasVehicularesRequest() {
        }
        
        public eliminarPolizasVehicularesRequest(int polizaId) {
            this.polizaId = polizaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPolizasVehicularesResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPolizasVehicularesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPolizasVehicularesResponse() {
        }
        
        public eliminarPolizasVehicularesResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class polizasVehicularesDTO : polizasDTO {
        
        private int porcentajeCoberturaField;
        
        private bool porcentajeCoberturaFieldSpecified;
        
        private tipoPolizaVehicular tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int porcentajeCobertura {
            get {
                return this.porcentajeCoberturaField;
            }
            set {
                this.porcentajeCoberturaField = value;
                this.RaisePropertyChanged("porcentajeCobertura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool porcentajeCoberturaSpecified {
            get {
                return this.porcentajeCoberturaFieldSpecified;
            }
            set {
                this.porcentajeCoberturaFieldSpecified = value;
                this.RaisePropertyChanged("porcentajeCoberturaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public tipoPolizaVehicular tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(polizasVehicularesDTO))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class polizasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private personasDTO aseguradoField;
        
        private estadoPoliza estadoField;
        
        private bool estadoFieldSpecified;
        
        private int polizaIdField;
        
        private bool polizaIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public personasDTO asegurado {
            get {
                return this.aseguradoField;
            }
            set {
                this.aseguradoField = value;
                this.RaisePropertyChanged("asegurado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoPoliza estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int polizaId {
            get {
                return this.polizaIdField;
            }
            set {
                this.polizaIdField = value;
                this.RaisePropertyChanged("polizaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool polizaIdSpecified {
            get {
                return this.polizaIdFieldSpecified;
            }
            set {
                this.polizaIdFieldSpecified = value;
                this.RaisePropertyChanged("polizaIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdPolizasVehiculares", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdPolizasVehicularesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int polizaId;
        
        public obtenerPorIdPolizasVehicularesRequest() {
        }
        
        public obtenerPorIdPolizasVehicularesRequest(int polizaId) {
            this.polizaId = polizaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdPolizasVehicularesResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdPolizasVehicularesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPolizasVehiculares.polizasVehicularesDTO @return;
        
        public obtenerPorIdPolizasVehicularesResponse() {
        }
        
        public obtenerPorIdPolizasVehicularesResponse(SiniNetBusiness.SiniNetWSPolizasVehiculares.polizasVehicularesDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosPolizasVehiculares", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosPolizasVehicularesRequest {
        
        public listarTodosPolizasVehicularesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosPolizasVehicularesResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosPolizasVehicularesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPolizasVehiculares.polizasVehicularesDTO[] @return;
        
        public listarTodosPolizasVehicularesResponse() {
        }
        
        public listarTodosPolizasVehicularesResponse(SiniNetBusiness.SiniNetWSPolizasVehiculares.polizasVehicularesDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPolizasVehiculares", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPolizasVehicularesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int polizaId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPolizasVehiculares.personasDTO asegurado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPolizasVehiculares.estadoPoliza estado;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPolizasVehiculares.tipoPolizaVehicular tipo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int porcentajeCobertura;
        
        public modificarPolizasVehicularesRequest() {
        }
        
        public modificarPolizasVehicularesRequest(int polizaId, SiniNetBusiness.SiniNetWSPolizasVehiculares.personasDTO asegurado, SiniNetBusiness.SiniNetWSPolizasVehiculares.estadoPoliza estado, SiniNetBusiness.SiniNetWSPolizasVehiculares.tipoPolizaVehicular tipo, int porcentajeCobertura) {
            this.polizaId = polizaId;
            this.asegurado = asegurado;
            this.estado = estado;
            this.tipo = tipo;
            this.porcentajeCobertura = porcentajeCobertura;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPolizasVehicularesResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPolizasVehicularesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPolizasVehicularesResponse() {
        }
        
        public modificarPolizasVehicularesResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorNombreApellidoAseguradoPolizasVehiculares", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorNombreApellidoAseguradoPolizasVehicularesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filtro;
        
        public listarPorNombreApellidoAseguradoPolizasVehicularesRequest() {
        }
        
        public listarPorNombreApellidoAseguradoPolizasVehicularesRequest(string filtro) {
            this.filtro = filtro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorNombreApellidoAseguradoPolizasVehicularesResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorNombreApellidoAseguradoPolizasVehicularesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPolizasVehiculares.polizasVehicularesDTO[] @return;
        
        public listarPorNombreApellidoAseguradoPolizasVehicularesResponse() {
        }
        
        public listarPorNombreApellidoAseguradoPolizasVehicularesResponse(SiniNetBusiness.SiniNetWSPolizasVehiculares.polizasVehicularesDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PolizasVehicularesChannel : SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PolizasVehicularesClient : System.ServiceModel.ClientBase<SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares>, SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares {
        
        public PolizasVehicularesClient() {
        }
        
        public PolizasVehicularesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PolizasVehicularesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolizasVehicularesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PolizasVehicularesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesResponse SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares.insertarPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesRequest request) {
            return base.Channel.insertarPolizasVehiculares(request);
        }
        
        public int insertarPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.personasDTO asegurado, SiniNetBusiness.SiniNetWSPolizasVehiculares.estadoPoliza estado, SiniNetBusiness.SiniNetWSPolizasVehiculares.tipoPolizaVehicular tipo, int porcentajeCobertura) {
            SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesRequest inValue = new SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesRequest();
            inValue.asegurado = asegurado;
            inValue.estado = estado;
            inValue.tipo = tipo;
            inValue.porcentajeCobertura = porcentajeCobertura;
            SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesResponse retVal = ((SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares)(this)).insertarPolizasVehiculares(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesResponse> SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares.insertarPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesRequest request) {
            return base.Channel.insertarPolizasVehicularesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesResponse> insertarPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.personasDTO asegurado, SiniNetBusiness.SiniNetWSPolizasVehiculares.estadoPoliza estado, SiniNetBusiness.SiniNetWSPolizasVehiculares.tipoPolizaVehicular tipo, int porcentajeCobertura) {
            SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesRequest inValue = new SiniNetBusiness.SiniNetWSPolizasVehiculares.insertarPolizasVehicularesRequest();
            inValue.asegurado = asegurado;
            inValue.estado = estado;
            inValue.tipo = tipo;
            inValue.porcentajeCobertura = porcentajeCobertura;
            return ((SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares)(this)).insertarPolizasVehicularesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesResponse SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares.eliminarPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesRequest request) {
            return base.Channel.eliminarPolizasVehiculares(request);
        }
        
        public int eliminarPolizasVehiculares(int polizaId) {
            SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesRequest inValue = new SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesRequest();
            inValue.polizaId = polizaId;
            SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesResponse retVal = ((SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares)(this)).eliminarPolizasVehiculares(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesResponse> SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares.eliminarPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesRequest request) {
            return base.Channel.eliminarPolizasVehicularesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesResponse> eliminarPolizasVehicularesAsync(int polizaId) {
            SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesRequest inValue = new SiniNetBusiness.SiniNetWSPolizasVehiculares.eliminarPolizasVehicularesRequest();
            inValue.polizaId = polizaId;
            return ((SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares)(this)).eliminarPolizasVehicularesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesResponse SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares.obtenerPorIdPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesRequest request) {
            return base.Channel.obtenerPorIdPolizasVehiculares(request);
        }
        
        public SiniNetBusiness.SiniNetWSPolizasVehiculares.polizasVehicularesDTO obtenerPorIdPolizasVehiculares(int polizaId) {
            SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesRequest inValue = new SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesRequest();
            inValue.polizaId = polizaId;
            SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesResponse retVal = ((SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares)(this)).obtenerPorIdPolizasVehiculares(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesResponse> SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares.obtenerPorIdPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesRequest request) {
            return base.Channel.obtenerPorIdPolizasVehicularesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesResponse> obtenerPorIdPolizasVehicularesAsync(int polizaId) {
            SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesRequest inValue = new SiniNetBusiness.SiniNetWSPolizasVehiculares.obtenerPorIdPolizasVehicularesRequest();
            inValue.polizaId = polizaId;
            return ((SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares)(this)).obtenerPorIdPolizasVehicularesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesResponse SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares.listarTodosPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesRequest request) {
            return base.Channel.listarTodosPolizasVehiculares(request);
        }
        
        public SiniNetBusiness.SiniNetWSPolizasVehiculares.polizasVehicularesDTO[] listarTodosPolizasVehiculares() {
            SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesRequest inValue = new SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesRequest();
            SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesResponse retVal = ((SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares)(this)).listarTodosPolizasVehiculares(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesResponse> SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares.listarTodosPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesRequest request) {
            return base.Channel.listarTodosPolizasVehicularesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesResponse> listarTodosPolizasVehicularesAsync() {
            SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesRequest inValue = new SiniNetBusiness.SiniNetWSPolizasVehiculares.listarTodosPolizasVehicularesRequest();
            return ((SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares)(this)).listarTodosPolizasVehicularesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesResponse SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares.modificarPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesRequest request) {
            return base.Channel.modificarPolizasVehiculares(request);
        }
        
        public int modificarPolizasVehiculares(int polizaId, SiniNetBusiness.SiniNetWSPolizasVehiculares.personasDTO asegurado, SiniNetBusiness.SiniNetWSPolizasVehiculares.estadoPoliza estado, SiniNetBusiness.SiniNetWSPolizasVehiculares.tipoPolizaVehicular tipo, int porcentajeCobertura) {
            SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesRequest inValue = new SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesRequest();
            inValue.polizaId = polizaId;
            inValue.asegurado = asegurado;
            inValue.estado = estado;
            inValue.tipo = tipo;
            inValue.porcentajeCobertura = porcentajeCobertura;
            SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesResponse retVal = ((SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares)(this)).modificarPolizasVehiculares(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesResponse> SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares.modificarPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesRequest request) {
            return base.Channel.modificarPolizasVehicularesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesResponse> modificarPolizasVehicularesAsync(int polizaId, SiniNetBusiness.SiniNetWSPolizasVehiculares.personasDTO asegurado, SiniNetBusiness.SiniNetWSPolizasVehiculares.estadoPoliza estado, SiniNetBusiness.SiniNetWSPolizasVehiculares.tipoPolizaVehicular tipo, int porcentajeCobertura) {
            SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesRequest inValue = new SiniNetBusiness.SiniNetWSPolizasVehiculares.modificarPolizasVehicularesRequest();
            inValue.polizaId = polizaId;
            inValue.asegurado = asegurado;
            inValue.estado = estado;
            inValue.tipo = tipo;
            inValue.porcentajeCobertura = porcentajeCobertura;
            return ((SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares)(this)).modificarPolizasVehicularesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesResponse SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehiculares(SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesRequest request) {
            return base.Channel.listarPorNombreApellidoAseguradoPolizasVehiculares(request);
        }
        
        public SiniNetBusiness.SiniNetWSPolizasVehiculares.polizasVehicularesDTO[] listarPorNombreApellidoAseguradoPolizasVehiculares(string filtro) {
            SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesRequest inValue = new SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesRequest();
            inValue.filtro = filtro;
            SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesResponse retVal = ((SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares)(this)).listarPorNombreApellidoAseguradoPolizasVehiculares(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesResponse> SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesAsync(SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesRequest request) {
            return base.Channel.listarPorNombreApellidoAseguradoPolizasVehicularesAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesResponse> listarPorNombreApellidoAseguradoPolizasVehicularesAsync(string filtro) {
            SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesRequest inValue = new SiniNetBusiness.SiniNetWSPolizasVehiculares.listarPorNombreApellidoAseguradoPolizasVehicularesRequest();
            inValue.filtro = filtro;
            return ((SiniNetBusiness.SiniNetWSPolizasVehiculares.PolizasVehiculares)(this)).listarPorNombreApellidoAseguradoPolizasVehicularesAsync(inValue);
        }
    }
}
