//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiniNetBusiness.SiniNetWSVehiculos {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class vehiculosDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string colorField;
        
        private marcaVehiculo marcaField;
        
        private bool marcaFieldSpecified;
        
        private string modeloField;
        
        private string placaField;
        
        private tipoVehiculo tipoField;
        
        private bool tipoFieldSpecified;
        
        private int vehiculoIdField;
        
        private bool vehiculoIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string color {
            get {
                return this.colorField;
            }
            set {
                this.colorField = value;
                this.RaisePropertyChanged("color");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public marcaVehiculo marca {
            get {
                return this.marcaField;
            }
            set {
                this.marcaField = value;
                this.RaisePropertyChanged("marca");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool marcaSpecified {
            get {
                return this.marcaFieldSpecified;
            }
            set {
                this.marcaFieldSpecified = value;
                this.RaisePropertyChanged("marcaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
                this.RaisePropertyChanged("modelo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
                this.RaisePropertyChanged("placa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public tipoVehiculo tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int vehiculoId {
            get {
                return this.vehiculoIdField;
            }
            set {
                this.vehiculoIdField = value;
                this.RaisePropertyChanged("vehiculoId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vehiculoIdSpecified {
            get {
                return this.vehiculoIdFieldSpecified;
            }
            set {
                this.vehiculoIdFieldSpecified = value;
                this.RaisePropertyChanged("vehiculoIdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum marcaVehiculo {
        
        /// <remarks/>
        TOYOTA,
        
        /// <remarks/>
        HYUNDAI,
        
        /// <remarks/>
        KIA,
        
        /// <remarks/>
        CHANGAN,
        
        /// <remarks/>
        CHEVROLET,
        
        /// <remarks/>
        JAC,
        
        /// <remarks/>
        DFSK,
        
        /// <remarks/>
        JETOUR,
        
        /// <remarks/>
        CHERY,
        
        /// <remarks/>
        FORD,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public enum tipoVehiculo {
        
        /// <remarks/>
        SEDAN,
        
        /// <remarks/>
        SUV,
        
        /// <remarks/>
        CAMIONETA,
        
        /// <remarks/>
        MOTOCICLETA,
        
        /// <remarks/>
        VAN,
        
        /// <remarks/>
        COUPE,
        
        /// <remarks/>
        MINIVAN,
        
        /// <remarks/>
        HATCHBACK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", ConfigurationName="SiniNetWSVehiculos.Vehiculos")]
    public interface Vehiculos {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/modificarVehiculosReque" +
            "st", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/modificarVehiculosRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosResponse modificarVehiculos(SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/modificarVehiculosReque" +
            "st", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/modificarVehiculosRespo" +
            "nse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosResponse> modificarVehiculosAsync(SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/obtenerPorIdVehiculosRe" +
            "quest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/obtenerPorIdVehiculosRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSVehiculos.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/obtenerPorIdVehiculos/F" +
            "ault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSVehiculos.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/obtenerPorIdVehiculos/F" +
            "ault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosResponse obtenerPorIdVehiculos(SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/obtenerPorIdVehiculosRe" +
            "quest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/obtenerPorIdVehiculosRe" +
            "sponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosResponse> obtenerPorIdVehiculosAsync(SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/eliminarVehiculosReques" +
            "t", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/eliminarVehiculosRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSVehiculos.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/eliminarVehiculos/Fault" +
            "/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSVehiculos.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/eliminarVehiculos/Fault" +
            "/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosResponse eliminarVehiculos(SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/eliminarVehiculosReques" +
            "t", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/eliminarVehiculosRespon" +
            "se")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosResponse> eliminarVehiculosAsync(SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/insertarVehiculosReques" +
            "t", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/insertarVehiculosRespon" +
            "se")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosResponse insertarVehiculos(SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/insertarVehiculosReques" +
            "t", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/insertarVehiculosRespon" +
            "se")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosResponse> insertarVehiculosAsync(SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/listarTodosVehiculosReq" +
            "uest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/listarTodosVehiculosRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSVehiculos.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/listarTodosVehiculos/Fa" +
            "ult/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSVehiculos.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/listarTodosVehiculos/Fa" +
            "ult/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosResponse listarTodosVehiculos(SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/listarTodosVehiculosReq" +
            "uest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/listarTodosVehiculosRes" +
            "ponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosResponse> listarTodosVehiculosAsync(SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/listarPorPlacaMarcaMode" +
            "loTipoVehiculoRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/listarPorPlacaMarcaMode" +
            "loTipoVehiculoResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSVehiculos.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/listarPorPlacaMarcaMode" +
            "loTipoVehiculo/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSVehiculos.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/listarPorPlacaMarcaMode" +
            "loTipoVehiculo/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoResponse listarPorPlacaMarcaModeloTipoVehiculo(SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/listarPorPlacaMarcaMode" +
            "loTipoVehiculoRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Vehiculos/listarPorPlacaMarcaMode" +
            "loTipoVehiculoResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoResponse> listarPorPlacaMarcaModeloTipoVehiculoAsync(SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarVehiculos", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarVehiculosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int vehiculoId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string placa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSVehiculos.marcaVehiculo marca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string color;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSVehiculos.tipoVehiculo tipo;
        
        public modificarVehiculosRequest() {
        }
        
        public modificarVehiculosRequest(int vehiculoId, string placa, SiniNetBusiness.SiniNetWSVehiculos.marcaVehiculo marca, string modelo, string color, SiniNetBusiness.SiniNetWSVehiculos.tipoVehiculo tipo) {
            this.vehiculoId = vehiculoId;
            this.placa = placa;
            this.marca = marca;
            this.modelo = modelo;
            this.color = color;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarVehiculosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarVehiculosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarVehiculosResponse() {
        }
        
        public modificarVehiculosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdVehiculos", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdVehiculosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int vehiculoId;
        
        public obtenerPorIdVehiculosRequest() {
        }
        
        public obtenerPorIdVehiculosRequest(int vehiculoId) {
            this.vehiculoId = vehiculoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdVehiculosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdVehiculosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSVehiculos.vehiculosDTO @return;
        
        public obtenerPorIdVehiculosResponse() {
        }
        
        public obtenerPorIdVehiculosResponse(SiniNetBusiness.SiniNetWSVehiculos.vehiculosDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarVehiculos", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarVehiculosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int vehiculoId;
        
        public eliminarVehiculosRequest() {
        }
        
        public eliminarVehiculosRequest(int vehiculoId) {
            this.vehiculoId = vehiculoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarVehiculosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarVehiculosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarVehiculosResponse() {
        }
        
        public eliminarVehiculosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVehiculos", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarVehiculosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string placa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSVehiculos.marcaVehiculo marca;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modelo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string color;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSVehiculos.tipoVehiculo tipo;
        
        public insertarVehiculosRequest() {
        }
        
        public insertarVehiculosRequest(string placa, SiniNetBusiness.SiniNetWSVehiculos.marcaVehiculo marca, string modelo, string color, SiniNetBusiness.SiniNetWSVehiculos.tipoVehiculo tipo) {
            this.placa = placa;
            this.marca = marca;
            this.modelo = modelo;
            this.color = color;
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVehiculosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarVehiculosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarVehiculosResponse() {
        }
        
        public insertarVehiculosResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosVehiculos", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosVehiculosRequest {
        
        public listarTodosVehiculosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosVehiculosResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosVehiculosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSVehiculos.vehiculosDTO[] @return;
        
        public listarTodosVehiculosResponse() {
        }
        
        public listarTodosVehiculosResponse(SiniNetBusiness.SiniNetWSVehiculos.vehiculosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorPlacaMarcaModeloTipoVehiculo", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorPlacaMarcaModeloTipoVehiculoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filtro;
        
        public listarPorPlacaMarcaModeloTipoVehiculoRequest() {
        }
        
        public listarPorPlacaMarcaModeloTipoVehiculoRequest(string filtro) {
            this.filtro = filtro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorPlacaMarcaModeloTipoVehiculoResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorPlacaMarcaModeloTipoVehiculoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSVehiculos.vehiculosDTO[] @return;
        
        public listarPorPlacaMarcaModeloTipoVehiculoResponse() {
        }
        
        public listarPorPlacaMarcaModeloTipoVehiculoResponse(SiniNetBusiness.SiniNetWSVehiculos.vehiculosDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VehiculosChannel : SiniNetBusiness.SiniNetWSVehiculos.Vehiculos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehiculosClient : System.ServiceModel.ClientBase<SiniNetBusiness.SiniNetWSVehiculos.Vehiculos>, SiniNetBusiness.SiniNetWSVehiculos.Vehiculos {
        
        public VehiculosClient() {
        }
        
        public VehiculosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehiculosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehiculosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosResponse SiniNetBusiness.SiniNetWSVehiculos.Vehiculos.modificarVehiculos(SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosRequest request) {
            return base.Channel.modificarVehiculos(request);
        }
        
        public int modificarVehiculos(int vehiculoId, string placa, SiniNetBusiness.SiniNetWSVehiculos.marcaVehiculo marca, string modelo, string color, SiniNetBusiness.SiniNetWSVehiculos.tipoVehiculo tipo) {
            SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosRequest inValue = new SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosRequest();
            inValue.vehiculoId = vehiculoId;
            inValue.placa = placa;
            inValue.marca = marca;
            inValue.modelo = modelo;
            inValue.color = color;
            inValue.tipo = tipo;
            SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosResponse retVal = ((SiniNetBusiness.SiniNetWSVehiculos.Vehiculos)(this)).modificarVehiculos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosResponse> SiniNetBusiness.SiniNetWSVehiculos.Vehiculos.modificarVehiculosAsync(SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosRequest request) {
            return base.Channel.modificarVehiculosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosResponse> modificarVehiculosAsync(int vehiculoId, string placa, SiniNetBusiness.SiniNetWSVehiculos.marcaVehiculo marca, string modelo, string color, SiniNetBusiness.SiniNetWSVehiculos.tipoVehiculo tipo) {
            SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosRequest inValue = new SiniNetBusiness.SiniNetWSVehiculos.modificarVehiculosRequest();
            inValue.vehiculoId = vehiculoId;
            inValue.placa = placa;
            inValue.marca = marca;
            inValue.modelo = modelo;
            inValue.color = color;
            inValue.tipo = tipo;
            return ((SiniNetBusiness.SiniNetWSVehiculos.Vehiculos)(this)).modificarVehiculosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosResponse SiniNetBusiness.SiniNetWSVehiculos.Vehiculos.obtenerPorIdVehiculos(SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosRequest request) {
            return base.Channel.obtenerPorIdVehiculos(request);
        }
        
        public SiniNetBusiness.SiniNetWSVehiculos.vehiculosDTO obtenerPorIdVehiculos(int vehiculoId) {
            SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosRequest inValue = new SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosRequest();
            inValue.vehiculoId = vehiculoId;
            SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosResponse retVal = ((SiniNetBusiness.SiniNetWSVehiculos.Vehiculos)(this)).obtenerPorIdVehiculos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosResponse> SiniNetBusiness.SiniNetWSVehiculos.Vehiculos.obtenerPorIdVehiculosAsync(SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosRequest request) {
            return base.Channel.obtenerPorIdVehiculosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosResponse> obtenerPorIdVehiculosAsync(int vehiculoId) {
            SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosRequest inValue = new SiniNetBusiness.SiniNetWSVehiculos.obtenerPorIdVehiculosRequest();
            inValue.vehiculoId = vehiculoId;
            return ((SiniNetBusiness.SiniNetWSVehiculos.Vehiculos)(this)).obtenerPorIdVehiculosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosResponse SiniNetBusiness.SiniNetWSVehiculos.Vehiculos.eliminarVehiculos(SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosRequest request) {
            return base.Channel.eliminarVehiculos(request);
        }
        
        public int eliminarVehiculos(int vehiculoId) {
            SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosRequest inValue = new SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosRequest();
            inValue.vehiculoId = vehiculoId;
            SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosResponse retVal = ((SiniNetBusiness.SiniNetWSVehiculos.Vehiculos)(this)).eliminarVehiculos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosResponse> SiniNetBusiness.SiniNetWSVehiculos.Vehiculos.eliminarVehiculosAsync(SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosRequest request) {
            return base.Channel.eliminarVehiculosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosResponse> eliminarVehiculosAsync(int vehiculoId) {
            SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosRequest inValue = new SiniNetBusiness.SiniNetWSVehiculos.eliminarVehiculosRequest();
            inValue.vehiculoId = vehiculoId;
            return ((SiniNetBusiness.SiniNetWSVehiculos.Vehiculos)(this)).eliminarVehiculosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosResponse SiniNetBusiness.SiniNetWSVehiculos.Vehiculos.insertarVehiculos(SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosRequest request) {
            return base.Channel.insertarVehiculos(request);
        }
        
        public int insertarVehiculos(string placa, SiniNetBusiness.SiniNetWSVehiculos.marcaVehiculo marca, string modelo, string color, SiniNetBusiness.SiniNetWSVehiculos.tipoVehiculo tipo) {
            SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosRequest inValue = new SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosRequest();
            inValue.placa = placa;
            inValue.marca = marca;
            inValue.modelo = modelo;
            inValue.color = color;
            inValue.tipo = tipo;
            SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosResponse retVal = ((SiniNetBusiness.SiniNetWSVehiculos.Vehiculos)(this)).insertarVehiculos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosResponse> SiniNetBusiness.SiniNetWSVehiculos.Vehiculos.insertarVehiculosAsync(SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosRequest request) {
            return base.Channel.insertarVehiculosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosResponse> insertarVehiculosAsync(string placa, SiniNetBusiness.SiniNetWSVehiculos.marcaVehiculo marca, string modelo, string color, SiniNetBusiness.SiniNetWSVehiculos.tipoVehiculo tipo) {
            SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosRequest inValue = new SiniNetBusiness.SiniNetWSVehiculos.insertarVehiculosRequest();
            inValue.placa = placa;
            inValue.marca = marca;
            inValue.modelo = modelo;
            inValue.color = color;
            inValue.tipo = tipo;
            return ((SiniNetBusiness.SiniNetWSVehiculos.Vehiculos)(this)).insertarVehiculosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosResponse SiniNetBusiness.SiniNetWSVehiculos.Vehiculos.listarTodosVehiculos(SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosRequest request) {
            return base.Channel.listarTodosVehiculos(request);
        }
        
        public SiniNetBusiness.SiniNetWSVehiculos.vehiculosDTO[] listarTodosVehiculos() {
            SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosRequest inValue = new SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosRequest();
            SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosResponse retVal = ((SiniNetBusiness.SiniNetWSVehiculos.Vehiculos)(this)).listarTodosVehiculos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosResponse> SiniNetBusiness.SiniNetWSVehiculos.Vehiculos.listarTodosVehiculosAsync(SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosRequest request) {
            return base.Channel.listarTodosVehiculosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosResponse> listarTodosVehiculosAsync() {
            SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosRequest inValue = new SiniNetBusiness.SiniNetWSVehiculos.listarTodosVehiculosRequest();
            return ((SiniNetBusiness.SiniNetWSVehiculos.Vehiculos)(this)).listarTodosVehiculosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoResponse SiniNetBusiness.SiniNetWSVehiculos.Vehiculos.listarPorPlacaMarcaModeloTipoVehiculo(SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoRequest request) {
            return base.Channel.listarPorPlacaMarcaModeloTipoVehiculo(request);
        }
        
        public SiniNetBusiness.SiniNetWSVehiculos.vehiculosDTO[] listarPorPlacaMarcaModeloTipoVehiculo(string filtro) {
            SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoRequest inValue = new SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoRequest();
            inValue.filtro = filtro;
            SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoResponse retVal = ((SiniNetBusiness.SiniNetWSVehiculos.Vehiculos)(this)).listarPorPlacaMarcaModeloTipoVehiculo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoResponse> SiniNetBusiness.SiniNetWSVehiculos.Vehiculos.listarPorPlacaMarcaModeloTipoVehiculoAsync(SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoRequest request) {
            return base.Channel.listarPorPlacaMarcaModeloTipoVehiculoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoResponse> listarPorPlacaMarcaModeloTipoVehiculoAsync(string filtro) {
            SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoRequest inValue = new SiniNetBusiness.SiniNetWSVehiculos.listarPorPlacaMarcaModeloTipoVehiculoRequest();
            inValue.filtro = filtro;
            return ((SiniNetBusiness.SiniNetWSVehiculos.Vehiculos)(this)).listarPorPlacaMarcaModeloTipoVehiculoAsync(inValue);
        }
    }
}
