//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiniNetBusiness.SiniNetWSPersonas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class personasDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string dniField;
        
        private string nombresField;
        
        private int personalIdField;
        
        private bool personalIdFieldSpecified;
        
        private string telefonoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
                this.RaisePropertyChanged("apellidoMaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
                this.RaisePropertyChanged("apellidoPaterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("nombres");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int personalId {
            get {
                return this.personalIdField;
            }
            set {
                this.personalIdField = value;
                this.RaisePropertyChanged("personalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool personalIdSpecified {
            get {
                return this.personalIdFieldSpecified;
            }
            set {
                this.personalIdFieldSpecified = value;
                this.RaisePropertyChanged("personalIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", ConfigurationName="SiniNetWSPersonas.Personas")]
    public interface Personas {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/obtenerPorIdPersonasRequ" +
            "est", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/obtenerPorIdPersonasResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPersonas.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/obtenerPorIdPersonas/Fau" +
            "lt/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPersonas.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/obtenerPorIdPersonas/Fau" +
            "lt/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasResponse obtenerPorIdPersonas(SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/obtenerPorIdPersonasRequ" +
            "est", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/obtenerPorIdPersonasResp" +
            "onse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasResponse> obtenerPorIdPersonasAsync(SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/eliminarPersonasRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/eliminarPersonasResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPersonas.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/eliminarPersonas/Fault/I" +
            "OException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPersonas.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/eliminarPersonas/Fault/I" +
            "nterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasResponse eliminarPersonas(SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/eliminarPersonasRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/eliminarPersonasResponse" +
            "")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasResponse> eliminarPersonasAsync(SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/modificarPersonasRequest" +
            "", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/modificarPersonasRespons" +
            "e")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPersonas.modificarPersonasResponse modificarPersonas(SiniNetBusiness.SiniNetWSPersonas.modificarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/modificarPersonasRequest" +
            "", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/modificarPersonasRespons" +
            "e")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.modificarPersonasResponse> modificarPersonasAsync(SiniNetBusiness.SiniNetWSPersonas.modificarPersonasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarTodosPersonasReque" +
            "st", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarTodosPersonasRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPersonas.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarTodosPersonas/Faul" +
            "t/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPersonas.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarTodosPersonas/Faul" +
            "t/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasResponse listarTodosPersonas(SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarTodosPersonasReque" +
            "st", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarTodosPersonasRespo" +
            "nse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasResponse> listarTodosPersonasAsync(SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/insertarPersonasRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/insertarPersonasResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPersonas.insertarPersonasResponse insertarPersonas(SiniNetBusiness.SiniNetWSPersonas.insertarPersonasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/insertarPersonasRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/insertarPersonasResponse" +
            "")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.insertarPersonasResponse> insertarPersonasAsync(SiniNetBusiness.SiniNetWSPersonas.insertarPersonasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarAseguradosPorSinie" +
            "stroRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarAseguradosPorSinie" +
            "stroResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPersonas.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarAseguradosPorSinie" +
            "stro/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPersonas.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarAseguradosPorSinie" +
            "stro/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroResponse listarAseguradosPorSiniestro(SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarAseguradosPorSinie" +
            "stroRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarAseguradosPorSinie" +
            "stroResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroResponse> listarAseguradosPorSiniestroAsync(SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarPorNombresApellido" +
            "sDniPersonaRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarPorNombresApellido" +
            "sDniPersonaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPersonas.IOException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarPorNombresApellido" +
            "sDniPersona/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SiniNetBusiness.SiniNetWSPersonas.InterruptedException), Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarPorNombresApellido" +
            "sDniPersona/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaResponse listarPorNombresApellidosDniPersona(SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarPorNombresApellido" +
            "sDniPersonaRequest", ReplyAction="http://softasegws.services.softaseg.pucp.edu.pe/Personas/listarPorNombresApellido" +
            "sDniPersonaResponse")]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaResponse> listarPorNombresApellidosDniPersonaAsync(SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdPersonas", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdPersonasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personalId;
        
        public obtenerPorIdPersonasRequest() {
        }
        
        public obtenerPorIdPersonasRequest(int personalId) {
            this.personalId = personalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdPersonasResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPersonas.personasDTO @return;
        
        public obtenerPorIdPersonasResponse() {
        }
        
        public obtenerPorIdPersonasResponse(SiniNetBusiness.SiniNetWSPersonas.personasDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPersonas", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPersonasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personalId;
        
        public eliminarPersonasRequest() {
        }
        
        public eliminarPersonasRequest(int personalId) {
            this.personalId = personalId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPersonasResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPersonasResponse() {
        }
        
        public eliminarPersonasResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPersonas", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPersonasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int personalId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        public modificarPersonasRequest() {
        }
        
        public modificarPersonasRequest(int personalId, string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono) {
            this.personalId = personalId;
            this.dni = dni;
            this.nombres = nombres;
            this.apellidoPaterno = apellidoPaterno;
            this.apellidoMaterno = apellidoMaterno;
            this.telefono = telefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPersonasResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPersonasResponse() {
        }
        
        public modificarPersonasResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosPersonas", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosPersonasRequest {
        
        public listarTodosPersonasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosPersonasResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPersonas.personasDTO[] @return;
        
        public listarTodosPersonasResponse() {
        }
        
        public listarTodosPersonasResponse(SiniNetBusiness.SiniNetWSPersonas.personasDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPersonas", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPersonasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombres;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoPaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoMaterno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefono;
        
        public insertarPersonasRequest() {
        }
        
        public insertarPersonasRequest(string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono) {
            this.dni = dni;
            this.nombres = nombres;
            this.apellidoPaterno = apellidoPaterno;
            this.apellidoMaterno = apellidoMaterno;
            this.telefono = telefono;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPersonasResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPersonasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPersonasResponse() {
        }
        
        public insertarPersonasResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAseguradosPorSiniestro", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAseguradosPorSiniestroRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSiniestro;
        
        public listarAseguradosPorSiniestroRequest() {
        }
        
        public listarAseguradosPorSiniestroRequest(int idSiniestro) {
            this.idSiniestro = idSiniestro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarAseguradosPorSiniestroResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarAseguradosPorSiniestroResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPersonas.personasDTO[] @return;
        
        public listarAseguradosPorSiniestroResponse() {
        }
        
        public listarAseguradosPorSiniestroResponse(SiniNetBusiness.SiniNetWSPersonas.personasDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorNombresApellidosDniPersona", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorNombresApellidosDniPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string filtro;
        
        public listarPorNombresApellidosDniPersonaRequest() {
        }
        
        public listarPorNombresApellidosDniPersonaRequest(string filtro) {
            this.filtro = filtro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorNombresApellidosDniPersonaResponse", WrapperNamespace="http://softasegws.services.softaseg.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorNombresApellidosDniPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softasegws.services.softaseg.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SiniNetBusiness.SiniNetWSPersonas.personasDTO[] @return;
        
        public listarPorNombresApellidosDniPersonaResponse() {
        }
        
        public listarPorNombresApellidosDniPersonaResponse(SiniNetBusiness.SiniNetWSPersonas.personasDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonasChannel : SiniNetBusiness.SiniNetWSPersonas.Personas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonasClient : System.ServiceModel.ClientBase<SiniNetBusiness.SiniNetWSPersonas.Personas>, SiniNetBusiness.SiniNetWSPersonas.Personas {
        
        public PersonasClient() {
        }
        
        public PersonasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasResponse SiniNetBusiness.SiniNetWSPersonas.Personas.obtenerPorIdPersonas(SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasRequest request) {
            return base.Channel.obtenerPorIdPersonas(request);
        }
        
        public SiniNetBusiness.SiniNetWSPersonas.personasDTO obtenerPorIdPersonas(int personalId) {
            SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasRequest();
            inValue.personalId = personalId;
            SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasResponse retVal = ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).obtenerPorIdPersonas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasResponse> SiniNetBusiness.SiniNetWSPersonas.Personas.obtenerPorIdPersonasAsync(SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasRequest request) {
            return base.Channel.obtenerPorIdPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasResponse> obtenerPorIdPersonasAsync(int personalId) {
            SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.obtenerPorIdPersonasRequest();
            inValue.personalId = personalId;
            return ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).obtenerPorIdPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasResponse SiniNetBusiness.SiniNetWSPersonas.Personas.eliminarPersonas(SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasRequest request) {
            return base.Channel.eliminarPersonas(request);
        }
        
        public int eliminarPersonas(int personalId) {
            SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasRequest();
            inValue.personalId = personalId;
            SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasResponse retVal = ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).eliminarPersonas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasResponse> SiniNetBusiness.SiniNetWSPersonas.Personas.eliminarPersonasAsync(SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasRequest request) {
            return base.Channel.eliminarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasResponse> eliminarPersonasAsync(int personalId) {
            SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.eliminarPersonasRequest();
            inValue.personalId = personalId;
            return ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).eliminarPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPersonas.modificarPersonasResponse SiniNetBusiness.SiniNetWSPersonas.Personas.modificarPersonas(SiniNetBusiness.SiniNetWSPersonas.modificarPersonasRequest request) {
            return base.Channel.modificarPersonas(request);
        }
        
        public int modificarPersonas(int personalId, string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono) {
            SiniNetBusiness.SiniNetWSPersonas.modificarPersonasRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.modificarPersonasRequest();
            inValue.personalId = personalId;
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            SiniNetBusiness.SiniNetWSPersonas.modificarPersonasResponse retVal = ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).modificarPersonas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.modificarPersonasResponse> SiniNetBusiness.SiniNetWSPersonas.Personas.modificarPersonasAsync(SiniNetBusiness.SiniNetWSPersonas.modificarPersonasRequest request) {
            return base.Channel.modificarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.modificarPersonasResponse> modificarPersonasAsync(int personalId, string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono) {
            SiniNetBusiness.SiniNetWSPersonas.modificarPersonasRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.modificarPersonasRequest();
            inValue.personalId = personalId;
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            return ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).modificarPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasResponse SiniNetBusiness.SiniNetWSPersonas.Personas.listarTodosPersonas(SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasRequest request) {
            return base.Channel.listarTodosPersonas(request);
        }
        
        public SiniNetBusiness.SiniNetWSPersonas.personasDTO[] listarTodosPersonas() {
            SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasRequest();
            SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasResponse retVal = ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).listarTodosPersonas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasResponse> SiniNetBusiness.SiniNetWSPersonas.Personas.listarTodosPersonasAsync(SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasRequest request) {
            return base.Channel.listarTodosPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasResponse> listarTodosPersonasAsync() {
            SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.listarTodosPersonasRequest();
            return ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).listarTodosPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPersonas.insertarPersonasResponse SiniNetBusiness.SiniNetWSPersonas.Personas.insertarPersonas(SiniNetBusiness.SiniNetWSPersonas.insertarPersonasRequest request) {
            return base.Channel.insertarPersonas(request);
        }
        
        public int insertarPersonas(string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono) {
            SiniNetBusiness.SiniNetWSPersonas.insertarPersonasRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.insertarPersonasRequest();
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            SiniNetBusiness.SiniNetWSPersonas.insertarPersonasResponse retVal = ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).insertarPersonas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.insertarPersonasResponse> SiniNetBusiness.SiniNetWSPersonas.Personas.insertarPersonasAsync(SiniNetBusiness.SiniNetWSPersonas.insertarPersonasRequest request) {
            return base.Channel.insertarPersonasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.insertarPersonasResponse> insertarPersonasAsync(string dni, string nombres, string apellidoPaterno, string apellidoMaterno, string telefono) {
            SiniNetBusiness.SiniNetWSPersonas.insertarPersonasRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.insertarPersonasRequest();
            inValue.dni = dni;
            inValue.nombres = nombres;
            inValue.apellidoPaterno = apellidoPaterno;
            inValue.apellidoMaterno = apellidoMaterno;
            inValue.telefono = telefono;
            return ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).insertarPersonasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroResponse SiniNetBusiness.SiniNetWSPersonas.Personas.listarAseguradosPorSiniestro(SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroRequest request) {
            return base.Channel.listarAseguradosPorSiniestro(request);
        }
        
        public SiniNetBusiness.SiniNetWSPersonas.personasDTO[] listarAseguradosPorSiniestro(int idSiniestro) {
            SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroRequest();
            inValue.idSiniestro = idSiniestro;
            SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroResponse retVal = ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).listarAseguradosPorSiniestro(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroResponse> SiniNetBusiness.SiniNetWSPersonas.Personas.listarAseguradosPorSiniestroAsync(SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroRequest request) {
            return base.Channel.listarAseguradosPorSiniestroAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroResponse> listarAseguradosPorSiniestroAsync(int idSiniestro) {
            SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.listarAseguradosPorSiniestroRequest();
            inValue.idSiniestro = idSiniestro;
            return ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).listarAseguradosPorSiniestroAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaResponse SiniNetBusiness.SiniNetWSPersonas.Personas.listarPorNombresApellidosDniPersona(SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaRequest request) {
            return base.Channel.listarPorNombresApellidosDniPersona(request);
        }
        
        public SiniNetBusiness.SiniNetWSPersonas.personasDTO[] listarPorNombresApellidosDniPersona(string filtro) {
            SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaRequest();
            inValue.filtro = filtro;
            SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaResponse retVal = ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).listarPorNombresApellidosDniPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaResponse> SiniNetBusiness.SiniNetWSPersonas.Personas.listarPorNombresApellidosDniPersonaAsync(SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaRequest request) {
            return base.Channel.listarPorNombresApellidosDniPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaResponse> listarPorNombresApellidosDniPersonaAsync(string filtro) {
            SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaRequest inValue = new SiniNetBusiness.SiniNetWSPersonas.listarPorNombresApellidosDniPersonaRequest();
            inValue.filtro = filtro;
            return ((SiniNetBusiness.SiniNetWSPersonas.Personas)(this)).listarPorNombresApellidosDniPersonaAsync(inValue);
        }
    }
}
